# translation of po_update-manager-ar.po to Arabic
# Arabic translation for update-manager
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the update-manager package.
#
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
# OsamaKhalid <osamak.wfm@gmail.com>, 2009.
#: ../DistUpgrade/DistUpgradeController.py:1075
msgid ""
msgstr ""
"Project-Id-Version: po_update-manager-ar\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2020-07-20 17:24-0700\n"
"PO-Revision-Date: 2019-06-18 17:52+0000\n"
"Last-Translator: Ibrahim Saed <ibraheem5000@gmail.com>\n"
"Language-Team: Arabic\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n % 100 >= "
"3 && n % 100 <= 10 ? 3 : n % 100 >= 11 && n % 100 <= 99 ? 4 : 5;\n"
"X-Launchpad-Export-Date: 2019-11-15 04:46+0000\n"
"X-Generator: Launchpad (build c597c3229eb023b1e626162d5947141bf7befb13)\n"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:215 ../DistUpgrade/distro.py:446
#, python-format
msgid "Server for %s"
msgstr "خادوم %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:233 ../DistUpgrade/distro.py:239
#: ../DistUpgrade/distro.py:255
msgid "Main server"
msgstr "الخادوم الرئيسي"

#: ../DistUpgrade/distro.py:259
msgid "Custom servers"
msgstr "خواديم مخصصة"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:151
msgid "Could not calculate sources.list entry"
msgstr "تعذر حساب مدخلة source.list"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:260
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr "تعذّر إيجاد أي ملفات حزم، لعل هذا ليس قرص أوبونتو أو البنية الخطأ؟"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:310
msgid "Failed to add the CD"
msgstr "فشلت إضافة الاسطوانة"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:311
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"حدث خطأ بإضافة القرص، ستلغى عملية الترقية. من فضلك قم بالإبلاغ عن هذا كعلّة "
"إذا كانت هذه إسطوانة صالحة لأوبونتو.\n"
"\n"
"رسالة الخطأ كانت:\n"
"'%s'"

#: ../DistUpgrade/DistUpgradeCache.py:180
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "أزل الحزمة التي في حالة سيئة"
msgstr[1] "أزل الحزمة التي في حالة سيئة"
msgstr[2] "أزل الحزمتين اللتين في حالة سيئة"
msgstr[3] "أزل الحزم التي في حالة سيئة"
msgstr[4] "أزل الحزم التي في حالة سيئة"
msgstr[5] "أزل الحزم التي في حالة سيئة"

#: ../DistUpgrade/DistUpgradeCache.py:183
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"حالة الحزمة '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. أتريد "
"إزالة هذه الحزمة الآن للمتابعة؟"
msgstr[1] ""
"حالة الحزمة '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. أتريد "
"إزالة هذه الحزمة الآن للمتابعة؟"
msgstr[2] ""
"حالة الحزمتين '%s' متضاربة وتحتاجان أن يعاد تثبيتهما، لكن لا أرشيف وجد لهما. "
"أتريد إزالة هذين الحزمتين الآن للمتابعة؟"
msgstr[3] ""
"حالة الحزم '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. أتريد "
"إزالة هذه الحزم الآن للمتابعة؟"
msgstr[4] ""
"حالة الحزم '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. أتريد "
"إزالة هذه الحزم الآن للمتابعة؟"
msgstr[5] ""
"حالة الحزم '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. أتريد "
"إزالة هذه الحزم الآن للمتابعة؟"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:299
msgid "The server may be overloaded"
msgstr "قد يكون الخادوم مثقلاً."

#: ../DistUpgrade/DistUpgradeCache.py:412
msgid "Broken packages"
msgstr "حزم معطوبة"

#: ../DistUpgrade/DistUpgradeCache.py:413
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"نظامك يحوي حزما مكسورة لا يمكن إصلاحها بهذه البرمجية. أصلحها مستخدما سينابتك "
"أو apt-get قبل المواصلة."

#: ../DistUpgrade/DistUpgradeCache.py:658
#, fuzzy, python-format
msgid "Broken packages after upgrade: %s"
msgstr "حزم معطوبة"

#. the most likely problem is the 3rd party pkgs so don't address
#. foreignPkgs and devRelease being True
#: ../DistUpgrade/DistUpgradeCache.py:667
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
" "
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:670
msgid ""
"This was likely caused by:\n"
" * Unofficial software packages not provided by Ubuntu\n"
"Please use the tool 'ppa-purge' from the ppa-purge \n"
"package to remove software from a Launchpad PPA and \n"
"try the upgrade again.\n"
"\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:678
msgid ""
"This was caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
"This is most likely a transient problem, \n"
"please try again later.\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:685
msgid "This is most likely a transient problem, please try again later."
msgstr "هذا على الأغلب عطل عابر، من فضلك حاول لاحقا."

#: ../DistUpgrade/DistUpgradeCache.py:688
msgid ""
"If none of this applies, then please report this bug using the command "
"'ubuntu-bug ubuntu-release-upgrader-core' in a terminal. "
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:690
msgid ""
"If you want to investigate this yourself the log files in '/var/log/dist-"
"upgrade' will contain details about the upgrade. Specifically, look at 'main."
"log' and 'apt.log'."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:696
msgid "Could not calculate the upgrade"
msgstr "تعذّر حساب الترقية"

#: ../DistUpgrade/DistUpgradeCache.py:755
msgid "Error authenticating some packages"
msgstr "خطأ في استيثاق بعض الحزم"

#: ../DistUpgrade/DistUpgradeCache.py:756
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"تعذّر استيثاق بعض الحزم. قد تكون هذه مشكلة عابرة في الشبكة، وقد تفلح المحاولة "
"مجددا لاحقا. طالع قائمة الحزم غير المتوثقة أدناه."

#: ../DistUpgrade/DistUpgradeCache.py:777
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr "الحزمة '%s' معلّمة للإزالة لكنها في قائمة الحذف السوداء."

#: ../DistUpgrade/DistUpgradeCache.py:783
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "الحزمة الأساسية '%s' معلّمة للإزالة."

#: ../DistUpgrade/DistUpgradeCache.py:792
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr "يحاول تثبيت نسخة في القائمة السوداء '%s'"

#: ../DistUpgrade/DistUpgradeCache.py:914
#, python-format
msgid "Can't install '%s'"
msgstr "تعذّر تثبيت '%s'"

#: ../DistUpgrade/DistUpgradeCache.py:915
msgid ""
"It was impossible to install a required package. Please report this as a bug "
"using 'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
msgstr ""
"كان من المستحيل تثبيت حزمة مطلوبة. رجاءً أبلغ عن هذه العلة باستخدام الأمر "
"'ubuntu-bug ubuntu-release-upgrader-core' في طرفية."

#: ../DistUpgrade/DistUpgradeCache.py:926
msgid "Can't guess meta-package"
msgstr "تعذّرت معرفة الحزمة الفوقية"

#: ../DistUpgrade/DistUpgradeCache.py:927
#, python-format
msgid ""
"Your system does not contain a %s or %s package and it was not possible to "
"detect which version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"نظامك الحالي لا يحتوي أيا من الحزم %s أو %s ولم يكن من الممكن الكشف عن نسخة "
"أوبونتو التي تستعملها حاليا.\n"
" رجاءً ثبت إحدى الحزم المذكورة أعلاه باستخدام synaptic أو apt-get قبل "
"المواصلة."

#: ../DistUpgrade/DistUpgradeController.py:113
msgid "Reading cache"
msgstr "يقرأ المخبئية"

#: ../DistUpgrade/DistUpgradeController.py:225
msgid "Unable to get exclusive lock"
msgstr "تعذّر على الحصول على قفل كامل"

#: ../DistUpgrade/DistUpgradeController.py:226
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"يعني هذا عادة أن تطبيق إدارة حزم آخر (مثل apt-get أو aptitude) يعمل حاليًا. "
"يرجى علق ذالك التطبيق أولًا."

#: ../DistUpgrade/DistUpgradeController.py:284
msgid "Upgrading over remote connection not supported"
msgstr "الترقية عبر اتصال بعيد غير مدعومة"

#: ../DistUpgrade/DistUpgradeController.py:285
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"لقد قمت بتشغيل الترقية عبر اتصال الغطاء الأمني عن بعد مع واجهة لا تدعم هذا. "
"الرجاء محاولة ترقية في وضع النص مع'do-release-upgrade'.\n"
"\n"
"سيتم الخروج من عملية الترقية الآن. الرجاء المحاولة بدون الغطاء الأمني."

#: ../DistUpgrade/DistUpgradeController.py:299
msgid "Continue running under SSH?"
msgstr "أتريد مواصلة العمل تحت SSH؟"

#: ../DistUpgrade/DistUpgradeController.py:300
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"يبدو أن هذه الجلسة تعمل خلال الغطاء الأمني. لا يوصَى بإجراء الترقية عبر "
"الغطاء الأمني حاليا لأنه في حال الفشل سيكون استرداده أصعب.\n"
"إذا استمررت، سيتم بدأ عفريت غطاء أمني إضافي على منفذ '%s'.\n"
"هل تريد الاستمرار؟"

#: ../DistUpgrade/DistUpgradeController.py:314
msgid "Starting additional sshd"
msgstr "يشغّل sshd إضافي"

#: ../DistUpgrade/DistUpgradeController.py:315
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"لتسهيل الإصلاح في حالة الفشل فإن sshd إضافيا سيُشغّل على المنفذ '%s'. إذا حدث "
"عطل في ssh المشتغل حاليا يمكنك الاتصال بالإضافي.\n"

#: ../DistUpgrade/DistUpgradeController.py:323
#, python-format
msgid ""
"If you run a firewall, you may need to temporarily open this port. As this "
"is potentially dangerous it's not done automatically. You can open the port "
"with e.g.:\n"
"'%s'"
msgstr ""
"إذا كان الجدار الناري يعمل، فربما تحتاج إلى فتح هذا المنفذ مؤقتاً. وحيث من "
"المحتمل أن يكون هذا خطراً لا يتم فتحه تقائياً. بإمكانك فتح المنفذ عن طريق:\n"
"'%s'"

#: ../DistUpgrade/DistUpgradeController.py:401
#: ../DistUpgrade/DistUpgradeController.py:425
msgid "Can not upgrade"
msgstr "تعذّرت الترقية"

#: ../DistUpgrade/DistUpgradeController.py:402
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr "ترقية من '%s' إلى '%s' غير مدعومة بهذه الأداة."

#: ../DistUpgrade/DistUpgradeController.py:426
msgid ""
"Your python3 install is corrupted. Please fix the '/usr/bin/python3' symlink."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:455
#, python-format
msgid "Can not write to '%s'"
msgstr "لا يمكن الكتابة إلى '%s'"

#: ../DistUpgrade/DistUpgradeController.py:456
#, python-format
msgid ""
"Its not possible to write to the system directory '%s' on your system. The "
"upgrade can not continue.\n"
"Please make sure that the system directory is writable."
msgstr ""
"لا يمكن الكتابة إلى مُجلد النظام '%s' على نظامك. لا يُمكن مُتابعة الترقية.\n"
"رجاءً تأكد أن مُجلد النظام قابل للكتابة."

#: ../DistUpgrade/DistUpgradeController.py:467
msgid "Include latest updates from the Internet?"
msgstr "أأضمن آخر التحديثات من الإنترنت؟"

#: ../DistUpgrade/DistUpgradeController.py:468
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""
"نظام الترقية يمكن أن يستخدم الإنرتنت للتنزيل التلقائي لآخر التحديثات ويثبتها "
"أثناء الترقية. إذا كنت تمتلك اتصال شبكة هذا موصى به بشدة.\n"
"\n"
"الترقية سوف تستغرق وقتا أطول، لكن عندما تكتمل، سيكون نظامك محدث تماما. "
"تستطيع اختيار عدم فعل ذلك، لكن يتعيّن عليك تثبيت آخر التحديثات بعد الترقية "
"مباشرة.\n"
"إذا كانت إجابتك 'لا' هنا، لن تستخدم الشبكة مطلقا."

#: ../DistUpgrade/DistUpgradeController.py:646
#, python-format
msgid "Not for humans during development stage of release %s"
msgstr "ليس للآدميين أثناء مرحلة تطوير الإصدارة %s"

#: ../DistUpgrade/DistUpgradeController.py:747
#, python-format
msgid "disabled on upgrade to %s"
msgstr "عُطّل عند الترقية إلى %s"

#: ../DistUpgrade/DistUpgradeController.py:804
msgid "No valid sources.list entry found"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:805
#, python-format
msgid ""
"While scanning your repository information no entry about %s could be "
"found.\n"
"\n"
"An upgrade might not succeed.\n"
"\n"
"Do you want to continue anyway?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:817
msgid "No valid mirror found"
msgstr "لم يُعثر على رابط بديل سليم"

#: ../DistUpgrade/DistUpgradeController.py:818
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run an internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"تعذر إيجاد رابط بديل للترقية أثناء البحث في معلومات المستودعات في حاسوبك. قد "
"يحدث هذا إن استخدمت رابط بديل داخلي أو إن كانت معلومات الرابط البديل قديمة.\n"
"\n"
"هل تود التعديل على ملف 'sources.list' لديك على أية حال؟ إذا أجبت ﺑـ'نعم' "
"فستُحدّث كل '%s' إلى '%s'. وإن أجبت ﺑـ'ﻻ' فستُلغى عملية الترقية."

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:838
msgid "Generate default sources?"
msgstr "أأولد المصادر المبدئية؟"

#: ../DistUpgrade/DistUpgradeController.py:839
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"تعذر إيجاد مدخلة صالحة لـ'%s' أثناء البحث في ملف 'sources.list' في حاسوبك.\n"
"\n"
"هل تود إضافة المدخلات الافتراضية لـ'%s'؟ إن أجبت ﺑ'ﻻ' فستُلغى عملية الترقية."

#: ../DistUpgrade/DistUpgradeController.py:874
#: ../DistUpgrade/DistUpgradeController.py:880
msgid "Repository information invalid"
msgstr "معلومات المستودع غير صحيحة"

#: ../DistUpgrade/DistUpgradeController.py:875
msgid ""
"Upgrading the repository information resulted in a invalid file so a bug "
"reporting process is being started."
msgstr ""
"ترقية معلومات المستودعات أسفرت عن ملف غير صالح، لذلك يجري بدء عملية للإبلاغ "
"عن العلّة."

#: ../DistUpgrade/DistUpgradeController.py:881
msgid ""
"Upgrading the repository information resulted in a invalid file. To report a "
"bug install apport and then execute 'apport-bug ubuntu-release-upgrader'."
msgstr ""
"ترقية معلومات المستودعات أسفرت عن ملف غير صالح. للإبلاغ عن المشكلة ثبّت "
"apport ثم نفّذ الأمر 'apport-bug ubuntu-release-upgrader' في الطرفية."

#: ../DistUpgrade/DistUpgradeController.py:890
msgid "Third party sources disabled"
msgstr "مصادر الأطراف الخارجية عُطّلت"

#: ../DistUpgrade/DistUpgradeController.py:891
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"بعض مدخلات الأطراف الخارجية في sources.list قد عطلت. يمكنك إعادة تفعيلها بعد "
"الترقية، باستخدام أداة 'software-properties' في مدير الحزم."

#: ../DistUpgrade/DistUpgradeController.py:933
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "لا حزم في حالة غير متسقة"
msgstr[1] "حزمة واحدة في حالة غير متسقة"
msgstr[2] "حزمتان في حالة غير متسقة"
msgstr[3] "حزم في حالة غير متسقة"
msgstr[4] "حزم في حالة غير متسقة"
msgstr[5] "حزم في حالة غير متسقة"

#: ../DistUpgrade/DistUpgradeController.py:936
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"حالة الحزمة '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. من "
"فضلك أعد تثبيت الحزمة يدويا أو أزلها من النظام."
msgstr[1] ""
"حالة الحزمة '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. من "
"فضلك أعد تثبيت الحزمة يدويا أو أزلها من النظام."
msgstr[2] ""
"حالة الحزمتين '%s' متضاربة وتحتاجان أن يعاد تثبيتهما، لكن لا أرشيف وجد لهما. "
"من فضلك أعد تثبيت الحزمتين يدويا أو أزلهما من النظام."
msgstr[3] ""
"حالة الحزم '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. من "
"فضلك أعد تثبيت الحزم يدويا أو أزلها من النظام."
msgstr[4] ""
"حالة الحزم '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. من "
"فضلك أعد تثبيت الحزم يدويا أو أزلها من النظام."
msgstr[5] ""
"حالة الحزم '%s' متضاربة وتحتاج أن يعاد تثبيتها، لكن لا أرشيف وجد لها. من "
"فضلك أعد تثبيت الحزم يدويا أو أزلها من النظام."

#: ../DistUpgrade/DistUpgradeController.py:999
msgid "Error during update"
msgstr "عطل أثناء التحديث"

#: ../DistUpgrade/DistUpgradeController.py:1000
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"طرأت مشكلة أثناء التحديث. عادة ما يكون هذا نتيجة مشكلة ما في الشبكة، تحقق من "
"اتصالك الشبكي وحاول مجددا."

#: ../DistUpgrade/DistUpgradeController.py:1043
#: ../DistUpgrade/DistUpgradeController.py:1048
msgid "EFI System Partition (ESP) not usable"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1044
msgid ""
"Your EFI System Partition (ESP) is not mounted at /boot/efi. Please ensure "
"that it is properly configured and try again."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1049
msgid ""
"The EFI System Partition (ESP) mounted at /boot/efi is not writable. Please "
"mount this partition read-write and try again."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1056
msgid "Not enough free disk space"
msgstr "لا توجد مساحة كافية على القرص"

#. TRANSLATORS: you can change the order of the sentence,
#. make sure to keep all {str_*} string untranslated.
#: ../DistUpgrade/DistUpgradeController.py:1059
#, python-brace-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of {str_total} free space "
"on disk '{str_dir}'. Please free at least an additional {str_needed} of disk "
"space on '{str_dir}'. {str_remedy}"
msgstr ""

#. specific ways to resolve lack of free space
#: ../DistUpgrade/DistUpgradeController.py:1064
msgid ""
"Remove temporary packages of former installations using 'sudo apt clean'."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1066
msgid ""
"You can remove old kernels using 'sudo apt autoremove' and you could also "
"set COMPRESS=xz in /etc/initramfs-tools/initramfs.conf to reduce the size of "
"your initramfs."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1071
msgid ""
"Empty your trash and remove temporary packages of former installations using "
"'sudo apt-get clean'."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1074
msgid "Reboot to clean up files in /tmp."
msgstr ""

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:1113
#: ../DistUpgrade/DistUpgradeController.py:1989
#: ../DistUpgrade/DistUpgradeController.py:2039
msgid "Calculating the changes"
msgstr "يُحصي التغيرات"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:1157
msgid "Do you want to start the upgrade?"
msgstr "أتريد بدء التحديث الآن؟"

#: ../DistUpgrade/DistUpgradeController.py:1176
#, python-format
msgid ""
"Livepatch security updates are not available for Ubuntu %s. If you upgrade, "
"Livepatch will turn off."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1248
msgid "Upgrade canceled"
msgstr "أُلغيت الترقية"

#: ../DistUpgrade/DistUpgradeController.py:1249
msgid ""
"The upgrade will cancel now and the original system state will be restored. "
"You can resume the upgrade at a later time."
msgstr ""
"الترقية ستلغى وسيتم استعادة الحالة الأصلية للنظام. بإمكانك استئناف الترقية "
"في وقت لاحق."

#: ../DistUpgrade/DistUpgradeController.py:1255
#: ../DistUpgrade/DistUpgradeController.py:1400
msgid "Could not download the upgrades"
msgstr "تعذّر تنزيل الترقيات"

#: ../DistUpgrade/DistUpgradeController.py:1256
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far have been kept."
msgstr ""
"تم إلغاء الترقية. رجاءً افحص اتصالك بالإنترنت أو وسيط التثبيت وحاول مجددا. "
"جميع الملفات التي نزلت تم حفظها."

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1349
#: ../DistUpgrade/DistUpgradeController.py:1388
#: ../DistUpgrade/DistUpgradeController.py:1504
msgid "Error during commit"
msgstr "عطل أثناء الإيداع"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1351
#: ../DistUpgrade/DistUpgradeController.py:1390
#: ../DistUpgrade/DistUpgradeController.py:1543
msgid "Restoring original system state"
msgstr "يسترجع الحالة الأصلية للنظام"

#: ../DistUpgrade/DistUpgradeController.py:1352
#: ../DistUpgrade/DistUpgradeController.py:1367
#: ../DistUpgrade/DistUpgradeController.py:1391
msgid "Could not install the upgrades"
msgstr "تعذّر تثبيت الترقيات"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1357
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"لقد أُجهضت الترقية. قد يصبح نظامك في خالة غير مستقرة. سيُشغل الاستعفاء الآن "
"(dpkg --configure -a)."

#: ../DistUpgrade/DistUpgradeController.py:1362
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug in a browser at http://bugs.launchpad.net/ubuntu/"
"+source/ubuntu-release-upgrader/+filebug and attach the files in /var/log/"
"dist-upgrade/ to the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"رجاء أبلغ عن هذه العلة عبر المتصفح على العنوان http://bugs.launchpad.net/"
"ubuntu/+source/ubuntu-release-upgrader/+filebug وأرفق الملفات الموجودة في /"
"var/log/dist-upgrade/ في تقرير العلة.\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1401
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"لقد تم إلغاء الترقية. تحقق من اتصالك بالإنترنت أو وسيط التثبيت وحاول مجددا. "

#: ../DistUpgrade/DistUpgradeController.py:1429
msgid "Searching for obsolete software"
msgstr "يبحث عن برمجيات قديمة"

#: ../DistUpgrade/DistUpgradeController.py:1492
msgid "Remove obsolete packages?"
msgstr "أأزيل الحزم المبطلة؟"

#: ../DistUpgrade/DistUpgradeController.py:1493
#: ../data/gtkbuilder/DistUpgrade.ui.h:8
msgid "_Keep"
msgstr "ا_ستبق"

#: ../DistUpgrade/DistUpgradeController.py:1493
msgid "_Remove"
msgstr "أ_زل"

#: ../DistUpgrade/DistUpgradeController.py:1505
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr "طرأت مشكلة أثناء التنظيف. طالع الرسالة أدناه لمزيد من المعلومات. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1581
msgid "Required depends is not installed"
msgstr "اعتمادات مطلوبة غير مثبتة"

#: ../DistUpgrade/DistUpgradeController.py:1582
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "الاعتمادية المطلوبة '%s' ليست مثبتة. "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1849
#: ../DistUpgrade/DistUpgradeController.py:1939
msgid "Checking package manager"
msgstr "يفحص مدير الحزم"

#: ../DistUpgrade/DistUpgradeController.py:1855
#: ../DistUpgrade/DistUpgradeController.py:1861
msgid "Preparing the upgrade failed"
msgstr "فشل تجهيز الترقية"

#: ../DistUpgrade/DistUpgradeController.py:1856
msgid ""
"Preparing the system for the upgrade failed so a bug reporting process is "
"being started."
msgstr "فشل تحضير النظام للترقية، لذلك يجري بدء عملية للإبلاغ عن العلّة."

#: ../DistUpgrade/DistUpgradeController.py:1862
msgid ""
"Preparing the system for the upgrade failed. To report a bug install apport "
"and then execute 'apport-bug ubuntu-release-upgrader'."
msgstr ""
"فشل تحضير النظام للترقية. للإبلاغ عن المشكلة ثبّت apport ثم نفّذ الأمر 'apport-"
"bug ubuntu-release-upgrader' في الطرفية."

#: ../DistUpgrade/DistUpgradeController.py:1879
#: ../DistUpgrade/DistUpgradeController.py:1889
msgid "Getting upgrade prerequisites failed"
msgstr "فشل جلب متطلبات الترقية"

#: ../DistUpgrade/DistUpgradeController.py:1880
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Additionally, a bug reporting process is being started."
msgstr ""
"تعذّر على النظام الحصول على المتطلبات الأساسية للترقية. ستُلغى عملية الترقية "
"الآن، وسيُعاد النظام للحالة الأصلية.\n"
"\n"
"بالإضافة إلى ذلك، يجرى بدء عملية للإبلاغ عن العلّة."

#: ../DistUpgrade/DistUpgradeController.py:1890
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"To report a bug install apport and then execute 'apport-bug ubuntu-release-"
"upgrader'."
msgstr ""
"تعذّر على النظام  الحصول على المتطلبات الأساسية للترقية. ستُلغى عملية الترقية "
"الآن، وسيُعاد النظام للحالة الأصلية.\n"
"\n"
"للإبلاغ عن علّة، قم بتثبيت apport ثم نفّذ إجراء 'apport-bug ubuntu-release-"
"upgrader' في الطرفية."

#: ../DistUpgrade/DistUpgradeController.py:1923
msgid "Updating repository information"
msgstr "يحدّث معلومات المستودعات"

#: ../DistUpgrade/DistUpgradeController.py:1930
msgid "Failed to add the cdrom"
msgstr "فشل في إضافة القرص المدمج"

#: ../DistUpgrade/DistUpgradeController.py:1931
msgid "Sorry, adding the cdrom was not successful."
msgstr "عفواً، لم يتم إضافة القرص المدمج بنجاح."

#: ../DistUpgrade/DistUpgradeController.py:1966
msgid "Invalid package information"
msgstr "معلومات حزم غير صحيحة"

#: ../DistUpgrade/DistUpgradeController.py:1967
#, python-format
msgid ""
"After updating your package information, the essential package '%s' could "
"not be located. This may be because you have no official mirrors listed in "
"your software sources, or because of excessive load on the mirror you are "
"using. See /etc/apt/sources.list for the current list of configured software "
"sources.\n"
"In the case of an overloaded mirror, you may want to try the upgrade again "
"later."
msgstr ""
"بعد تحديث معلومات الحزمة، تعذّر تحديد موقع الحزمة الأساسية '%s' . قد يكون هذا "
"بسبب عدم وجود روابط بديلة في قائمة مصادر البرمجيات، أو بسبب الحِمل الزائد على "
"الروابط البديلة التي تستخدمها. أنظر في القائمة الحالية لمصادر البرمجيات /etc/"
"apt/sources.list .\n"
"\n"
"إذا كانت المشكلة بسبب الحِمل الزائد على الروابط البديلة، فربما عليك محاولة "
"الترقية لاحقا."

#: ../DistUpgrade/DistUpgradeController.py:1996
#: ../DistUpgrade/DistUpgradeController.py:2095
msgid "Fetching"
msgstr "يجلب"

#: ../DistUpgrade/DistUpgradeController.py:2003
#: ../DistUpgrade/DistUpgradeController.py:2024
#: ../DistUpgrade/DistUpgradeController.py:2045
#: ../DistUpgrade/DistUpgradeController.py:2099
msgid "Upgrading"
msgstr "تجري الترقية"

#: ../DistUpgrade/DistUpgradeController.py:2005
msgid "Upgrade infeasible"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:2006
msgid ""
"The upgrade could not be completed, there were errors during the upgrade "
"process."
msgstr ""

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:2027
msgid "Upgrade incomplete"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:2028
msgid ""
"The upgrade has partially completed but there were errors during the upgrade "
"process."
msgstr ""

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:2050
#: ../DistUpgrade/DistUpgradeController.py:2101
#: ../DistUpgrade/DistUpgradeController.py:2107
#: ../DistUpgrade/DistUpgradeController.py:2118
msgid "Upgrade complete"
msgstr "اكتملت الترقية"

#: ../DistUpgrade/DistUpgradeController.py:2051
#: ../DistUpgrade/DistUpgradeController.py:2102
#: ../DistUpgrade/DistUpgradeController.py:2108
msgid ""
"The upgrade has completed but there were errors during the upgrade process."
msgstr "الترقية اكتملت، ولكن كان هناك أخطاء أثناء عملية الترقية."

#: ../DistUpgrade/DistUpgradeController.py:2070
msgid "System upgrade is complete."
msgstr "تمت ترقية النظام."

#: ../DistUpgrade/DistUpgradeController.py:2119
msgid "The partial upgrade was completed."
msgstr "اكتملت الترقية الجزئية."

#: ../DistUpgrade/DistUpgradeController.py:2147
msgid "Lock screen disabled"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:2148
msgid ""
"Your lock screen has been disabled and will remain disabled until you reboot."
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcher.py:107
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:170
msgid "Could not find the release notes"
msgstr "تعذّر العثور على ملاحظات الإصدارة"

#: ../DistUpgrade/DistUpgradeFetcher.py:108
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:171
msgid "The server may be overloaded. "
msgstr "قد يكون الخادوم محملا فوق طاقته. "

#: ../DistUpgrade/DistUpgradeFetcher.py:120
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:175
msgid "Could not download the release notes"
msgstr "تعذّر تنزيل ملاحظات الإصدارة"

#: ../DistUpgrade/DistUpgradeFetcher.py:121
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:176
msgid "Please check your internet connection."
msgstr "رجاءً تحقق من اتصالك بالإنترنت."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:73
#, python-format
msgid "authenticate '%(file)s' against '%(signature)s' "
msgstr "توثيق '%(file)s' باستخدام البصمة '%(signature)s' "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:97
#, python-format
msgid "extracting '%s'"
msgstr "يستخرج '%s'"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:118
#: ../DistUpgrade/DistUpgradeFetcherCore.py:119
msgid "Could not run the upgrade tool"
msgstr "تعذّر تشغيل أداة الترقية"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:120
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug "
"using the command 'ubuntu-bug ubuntu-release-upgrader-core'."
msgstr ""
"على الأرجح، هذا خطأ في أداة الترقية. رجاءً أبلغ عن هذه العلة باستخدام الأمر "
"'ubuntu-bug ubuntu-release-upgrader-core'."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:197
msgid "Upgrade tool signature"
msgstr "توقيع أداة الترقية"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:204
msgid "Upgrade tool"
msgstr "أداة الترقية"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:238
msgid "Failed to fetch"
msgstr "فشل الجلب"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:239
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr "فشل جلب الترقية، قد تكون هناك مشكلة في الشبكة. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:243
msgid "Authentication failed"
msgstr "فشل الاستيثاق"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:244
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr "فشل استيثاق الترقية. قد توجد مشكلة في الشبكة أو في الخادوم. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:249
msgid "Failed to extract"
msgstr "فشل الاستخراج"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:250
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr "فشل استخلاص الترقية، قد تكون هناك مشكلة في الشبكة أو الخادوم. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:255
msgid "Verification failed"
msgstr "فشل التحقق"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:256
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr "فشل التحقق من الترقية. قد توجد مشكلة في الشبكة أو في الخادوم. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:270
#: ../DistUpgrade/DistUpgradeFetcherCore.py:276
msgid "Can not run the upgrade"
msgstr "لا يمكن اجراء الترقية"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:271
msgid ""
"This usually is caused by a system where /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"غالبًا ما يحدث هذا إذا ما تم تحميل /tmp بإشارة nonexec. رجاءً أعد التحميل بدون "
"nonexec ثم أعد تشغيل الترقية."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:277
#, python-format
msgid "The error message is '%s'."
msgstr "رسالة الخطأ هي '%s'."

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:151
msgid "&Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:154
#: ../DistUpgrade/DistUpgradeViewKDE.py:715
msgid "&Cancel"
msgstr "أل&غِ"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:156
#: ../data/gtkbuilder/ReleaseNotes.ui.h:1
msgid "Release Notes"
msgstr "ملاحظات الإصدار"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:191
msgid "Upgrade"
msgstr "رقّ"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:207
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:222
msgid "Downloading additional package files..."
msgstr "تنزيل ملفات الحزم الإضافية..."

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:224
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "الملف %s من %s بسرعة %s ب/ث"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:228
#, python-format
msgid "File %s of %s"
msgstr "ملف %s من %s"

#. print("mediaChange %s %s" % (medium, drive))
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:235
#: ../DistUpgrade/DistUpgradeViewGtk3.py:125
#: ../DistUpgrade/DistUpgradeViewKDE.py:302
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "رجاء أدرج '%s' في محرك الأقراص '%s'"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:237
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:242
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:243
#: ../DistUpgrade/DistUpgradeViewKDE.py:303
msgid "Media Change"
msgstr "تغيير الوسائط"

#: ../DistUpgrade/DistUpgradeQuirks.py:227
msgid "Your graphics hardware may not be fully supported in Ubuntu 14.04."
msgstr "قد يكون عتاد الرسوميات في جهازك ليس مدعوما بالكامل في أوبونتو 14.04."

#: ../DistUpgrade/DistUpgradeQuirks.py:229
msgid ""
"Running the 'unity' desktop environment is not fully supported by your "
"graphics hardware. You will maybe end up in a very slow environment after "
"the upgrade. Our advice is to keep the LTS version for now. For more "
"information see https://wiki.ubuntu.com/X/Bugs/"
"UpdateManagerWarningForUnity3D Do you still want to continue with the "
"upgrade?"
msgstr ""
"تشغيل بيئة سطح المكتب \"يونتي\" ليس مدعوما بالكامل من عتاد الرسوميات الخاص "
"بك. قد ينتهي بك الأمر في بيئة بطيئة جدا بعد الترقية. ننصحك بإبقاء الإصدارة "
"الحالية في الوقت الراهن. لمزيد من المعلومات، انظر: https://wiki.ubuntu.com/X/"
"Bugs/UpdateManagerWarningForUnity3D\r\n"
"هل ما زلت ترغب بالاستمرار في الترقية؟"

#: ../DistUpgrade/DistUpgradeQuirks.py:253
msgid "Your graphics hardware may not be fully supported in Ubuntu 12.04 LTS."
msgstr "قد يكون عتاد الرسوميات في جهازك غير مدعوم بالكامل في أوبنتو 12.04."

#: ../DistUpgrade/DistUpgradeQuirks.py:255
msgid ""
"The support in Ubuntu 12.04 LTS for your Intel graphics hardware is limited "
"and you may encounter problems after the upgrade. For more information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx Do you want to "
"continue with the upgrade?"
msgstr ""
"دعم أوبنتو 12.04 لعتاد الرسوميات في جهازك محدود وقد تواجه مشاكل بعد الترقية. "
"لمزيد من المعلومات انظر: https://wiki.ubuntu.com/X/Bugs/"
"UpdateManagerWarningForI8xx هل تود الاستمرار في الترقية؟"

#: ../DistUpgrade/DistUpgradeQuirks.py:275
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"قد تقلل الترقية من تأثيرات سطح المكتب، وأداء الألعاب وبرامج الرسوميات "
"المكثفة الأخرى."

#: ../DistUpgrade/DistUpgradeQuirks.py:279
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"يستخدم حاسوبك حاليا مشغل 'fglrx' لرسوميات AMD. لا توجد نسخة من هذا المشغل "
"متوافقة مع عتادك في أوبونتو 10.04 LTS.\n"
"\n"
"أتريد المواصلة؟"

#: ../DistUpgrade/DistUpgradeQuirks.py:318
msgid "Sorry, no more upgrades for this system"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:319
#, python-format
msgid ""
"There will not be any further Ubuntu releases for this system's 'i386' "
"architecture.\n"
"\n"
"Updates for Ubuntu %s will continue until %s."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:334
msgid "No ARMv6 CPU"
msgstr "لا معالج ARMv6"

#: ../DistUpgrade/DistUpgradeQuirks.py:335
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"نظامك يستخدم معالج ARM أقدم من معمارية ARMv6. إن جميع الحزم في النسخة karmic "
"مبنية لتعمل على الطراز ARMv6 كحد أدنى. من غير الممكن ترقية نظامك إلى إصدارة "
"أوبونتو حديثة مع هذا العتاد."

#: ../DistUpgrade/DistUpgradeQuirks.py:355
msgid "No init available"
msgstr "لا يوجد عفريت مدير للعمليات"

#: ../DistUpgrade/DistUpgradeQuirks.py:356
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"يبدو أن نظامك يعمل في بيئة ظاهرية بدون عفريت بدأ، مثلاً Linux-VServer. لا "
"يستطيع أوبنتو 10.04 د.ط.أ (دعم طويل الأمد) العمل في هذا النوع من بيئات "
"العمل، يتطلب تحديثًا لإعدادات الألة الظاهرية أولاً.\n"
"\n"
"هل حقاً تريد الاستمرار؟"

#: ../DistUpgrade/DistUpgradeQuirks.py:469
msgid "Connection to the Snap Store failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:470
msgid ""
"You have the package lxd installed but your system is unable to reach the "
"Snap Store. lxd is now provided via a snap and the release upgrade will fail "
"if snapd is not functional. Please make sure you're connected to the "
"Internet and update any firewall or proxy settings as needed so that you can "
"reach api.snapcraft.io. If you are an enterprise with a firewall setup you "
"may want to configure a Snap Store proxy."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:485
msgid "Connection to Snap Store failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:486
msgid ""
"Your system does not have a connection to the Snap Store. For the best "
"upgrade experience make sure that your system can connect to api.snapcraft."
"io.\n"
"Do you still want to continue with the upgrade?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:495
msgid "Outdated snapd package"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:496
msgid ""
"Your system does not have the latest version of snapd. Please update the "
"version of snapd on your system to improve the upgrade experience.\n"
"Do you still want to continue with the upgrade?"
msgstr ""

#. now perform direct API calls to the store, requesting size
#. information for each of the snaps needing installation
#: ../DistUpgrade/DistUpgradeQuirks.py:519
msgid "Calculating snap size requirements"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:550
msgid "Processing snap replacements"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:556
#, python-format
msgid "refreshing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:560
#, python-format
msgid "removing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:563
#, python-format
msgid "installing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:592
msgid "PAE not enabled"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:593
msgid ""
"Your system uses a CPU that does not have PAE enabled. Ubuntu only supports "
"non-PAE systems up to Ubuntu 12.04. To upgrade to a later version of Ubuntu, "
"you must enable PAE (if this is possible) see:\n"
"http://help.ubuntu.com/community/EnablingPAE"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:916
msgid "Checking for installed snaps"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:58
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr "ابحث في المسار المعطى عن قرص مدمج يحوي حزم ترقية"

#: ../DistUpgrade/DistUpgradeMain.py:64
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"استخدم واجهة. المتاح حاليا:\n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKD"

#: ../DistUpgrade/DistUpgradeMain.py:67
msgid "*DEPRECATED* this option will be ignored"
msgstr "*مهجور* سيتم تجاهل هذا الخيار"

#: ../DistUpgrade/DistUpgradeMain.py:70
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr "قم بترقية جزئية فقط (لا كتابة فوق sources.list)"

#: ../DistUpgrade/DistUpgradeMain.py:73
msgid "Disable GNU screen support"
msgstr "عطل دعم شاشة جنو"

#: ../DistUpgrade/DistUpgradeMain.py:75
msgid "Set datadir"
msgstr "حدد مجلد البيانات"

#: ../DistUpgrade/DistUpgradeMain.py:78
msgid "Upgrade to the development release"
msgstr "الترقية إلى الإصدارة التجريبية"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:146
#: ../DistUpgrade/DistUpgradeViewKDE.py:316
msgid "Fetching is complete"
msgstr "اكتمل الجلب"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:161
#: ../DistUpgrade/DistUpgradeViewKDE.py:332
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "يجلب الملف %li من %li بـ %s.بايت/ثانية"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:163
#: ../DistUpgrade/DistUpgradeViewGtk3.py:325
#: ../DistUpgrade/DistUpgradeViewKDE.py:333
#: ../DistUpgrade/DistUpgradeViewKDE.py:483
#, python-format
msgid "About %s remaining"
msgstr "بقي %s تقريبا"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:166
#: ../DistUpgrade/DistUpgradeViewKDE.py:335
#, python-format
msgid "Fetching file %li of %li"
msgstr "يجلب الملف %li من %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk3.py:198
#: ../DistUpgrade/DistUpgradeViewKDE.py:373
msgid "Applying changes"
msgstr "يطبّق التغييرات"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk3.py:224
#: ../DistUpgrade/DistUpgradeViewKDE.py:386
msgid "dependency problems - leaving unconfigured"
msgstr "مشكلة اعتمادية - سأغادر بدون إعداد"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:229
#: ../DistUpgrade/DistUpgradeViewKDE.py:388
#, python-format
msgid "Could not install '%s'"
msgstr "تعذّر تثبيت '%s'"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:230
#: ../DistUpgrade/DistUpgradeViewKDE.py:389
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr "ستواصل الترقية لكن حزمة '%s' قد لا تعمل. من فضلك أبلغ عن هذه العلة."

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk3.py:247
#: ../DistUpgrade/DistUpgradeViewKDE.py:411
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"أأستبدل الملف المطوع\n"
"'%s'؟"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:248
#: ../DistUpgrade/DistUpgradeViewKDE.py:412
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"ستفقد أي تغيرات كنت قد أحدثتها في ملف التضبيطات هذا إن اخترت استبداله "
"بإصدارة أحدث."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:268
#: ../DistUpgrade/DistUpgradeViewKDE.py:435
msgid "The 'diff' command was not found"
msgstr "تعذّر العثور على أمر 'diff'"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:535
#: ../DistUpgrade/DistUpgradeViewText.py:140
msgid "A fatal error occurred"
msgstr "حدث خطأ فادح"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:536
msgid ""
"Please report this as a bug (if you haven't already) and include the files /"
"var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"رجاءً أبلغ عن هذا كعلّة (إذا لم تكن قد فعلت) و أرفق الملفان /var/log/dist-"
"upgrade/main.log و /var/log/dist-upgrade/apt.log في البلاغ. تم الخروج من "
"الترقية.\n"
"ملف sources.list الأصلي حُفِظَ في /etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:566
msgid "Ctrl-c pressed"
msgstr "ضُغط Ctrl-c"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:567
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"هذا سيجهض العملية وقد يترك النظام في حالة معطوبة. أمتأكد أنك تريد فعل ذلك؟"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk3.py:706
msgid "To prevent data loss close all open applications and documents."
msgstr "لتلافي فقد البيانات أغلق جميع التطبيقات والمستندات."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:720
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr "لم تعد كانونيكال تدعمها (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:721
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr "<b>إلى إصدارة أقدم (%s)</b>"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:722
#, python-format
msgid "Remove (%s)"
msgstr "أزل (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:723
#, python-format
msgid "No longer needed (%s)"
msgstr "لم تعد مطلوبة (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:724
#, python-format
msgid "Install (%s)"
msgstr "تثبيت (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:725
#, python-format
msgid "Upgrade (%s)"
msgstr "ترقية (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:773
msgid "Cancel"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk3.py:774
#: ../DistUpgrade/DistUpgradeViewKDE.py:939
msgid "Continue"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:447
msgid "Show Difference >>>"
msgstr "أظهر الفرق >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:450
msgid "<<< Hide Difference"
msgstr "<<< أخف الفرق"

#: ../DistUpgrade/DistUpgradeViewKDE.py:701
msgid "Error"
msgstr "خطأ"

#: ../DistUpgrade/DistUpgradeViewKDE.py:719
#: ../DistUpgrade/DistUpgradeViewKDE.py:960
msgid "&Close"
msgstr "أ&غلق"

#: ../DistUpgrade/DistUpgradeViewKDE.py:753
msgid "Show Terminal >>>"
msgstr "أظهر الطرفية >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:756
msgid "<<< Hide Terminal"
msgstr "<<< أخف الطرفية"

#: ../DistUpgrade/DistUpgradeViewKDE.py:829
msgid "Information"
msgstr "معلومات"

#: ../DistUpgrade/DistUpgradeViewKDE.py:877
msgid "&Start Upgrade"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:879
#: ../DistUpgrade/DistUpgradeViewKDE.py:923
#: ../DistUpgrade/DistUpgradeViewKDE.py:926
#: ../data/gtkbuilder/DistUpgrade.ui.h:7
msgid "Details"
msgstr "التّفاصيل"

#: ../DistUpgrade/DistUpgradeViewKDE.py:901
#, python-format
msgid "No longer supported %s"
msgstr "لم تعد مدعومة %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:903
#, python-format
msgid "Remove %s"
msgstr "أزل %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:905
#: ../DistUpgrade/DistUpgradeViewText.py:239
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "أزل %s (ثبّت تلقائيا)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:907
#, python-format
msgid "Install %s"
msgstr "ثبّت %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:909
#, python-format
msgid "Upgrade %s"
msgstr "رقِّ %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:956
#: ../DistUpgrade/DistUpgradeViewText.py:292
msgid "Restart required"
msgstr "إعادة التشغيل مطلوبة"

#: ../DistUpgrade/DistUpgradeViewKDE.py:956
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>أعد تشغيل النظام لإتمام الترقية</big><b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:959
#: ../data/gtkbuilder/DistUpgrade.ui.h:14
msgid "_Restart Now"
msgstr "أ_عد التشغيل الآن"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:977
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>أألغ الترقية الجارية ؟</big></b>\n"
"\n"
"قد يصبح النظام في حالة غير صالحة للاستعمال إذا ألغيت الترقية. ننصح بشدة "
"استئناف الترقية."

#: ../DistUpgrade/DistUpgradeViewKDE.py:981
msgid "Cancel Upgrade?"
msgstr "أألغي الترقية؟"

#: ../DistUpgrade/DistUpgradeView.py:82
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "لا أيام"
msgstr[1] "يوم واحد"
msgstr[2] "يومان"
msgstr[3] "%li أيام"
msgstr[4] "%li يوما"
msgstr[5] "%li يوم"

#: ../DistUpgrade/DistUpgradeView.py:84
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "لا ساعات"
msgstr[1] "ساعة واحدة"
msgstr[2] "ساعاتان"
msgstr[3] "%li ساعات"
msgstr[4] "%li ساعة"
msgstr[5] "%li ساعة"

#: ../DistUpgrade/DistUpgradeView.py:86
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "لا دقائق"
msgstr[1] "دقيقة واحدة"
msgstr[2] "دقيقتان"
msgstr[3] "%li دقائق"
msgstr[4] "%li دقيقة"
msgstr[5] "%li دقيقة"

#: ../DistUpgrade/DistUpgradeView.py:87
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "لا ثوان"
msgstr[1] "ثانية واحدة"
msgstr[2] "ثانيتان"
msgstr[3] "%li ثوان"
msgstr[4] "%li ثانية"
msgstr[5] "%li ثانية"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:103
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:121
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:172
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"سيأخذ التنزيل حوالي %s على اتصال بسرعة 1م.بايت، وحوالي %s على مودم 56ك."

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:176
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "سيستغرق التنزيل حوالي %s بسرعة اتصالك. "

#. Declare these translatable strings from the .ui files here so that
#. xgettext picks them up.
#: ../DistUpgrade/DistUpgradeView.py:270 ../data/gtkbuilder/DistUpgrade.ui.h:22
msgid "Preparing to upgrade"
msgstr "يحضّر للترقية"

#: ../DistUpgrade/DistUpgradeView.py:271
msgid "Getting new software channels"
msgstr "يجلب قنوات البرمجيات الجديدة"

#: ../DistUpgrade/DistUpgradeView.py:272 ../data/gtkbuilder/DistUpgrade.ui.h:24
msgid "Getting new packages"
msgstr "يجلب الحزم الجديدة"

#: ../DistUpgrade/DistUpgradeView.py:273 ../data/gtkbuilder/DistUpgrade.ui.h:27
msgid "Installing the upgrades"
msgstr "يثبّت الترقيات"

#: ../DistUpgrade/DistUpgradeView.py:274 ../data/gtkbuilder/DistUpgrade.ui.h:26
msgid "Cleaning up"
msgstr "ينظّف"

#: ../DistUpgrade/DistUpgradeView.py:363
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
"ليس أي من الحزم المثبتة لم تعد كانونيكال تدعمه. مازال بإمكانك الحصول على "
"الدعم من المجتمع."
msgstr[1] ""
"واحدة من الحزم المثبتة لم تعد كانونيكال تدعمه. مازال بإمكانك الحصول على "
"الدعم من المجتمع."
msgstr[2] ""
"اثنتان من الحزم المثبتة لم تعد كانونيكال تدعمه. مازال بإمكانك الحصول على "
"الدعم من المجتمع."
msgstr[3] ""
"%(amount)d حزم من المثبتة لم تعد كانونيكال تدعمه. مازال بإمكانك الحصول على "
"الدعم من المجتمع."
msgstr[4] ""
"%(amount)d حزمة من المثبتة لم تعد كانونيكال تدعمه. مازال بإمكانك الحصول على "
"الدعم من المجتمع."
msgstr[5] ""
"%(amount)d حزمة من المثبتة لم تعد كانونيكال تدعمه. مازال بإمكانك الحصول على "
"الدعم من المجتمع."

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:372
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "لن تزال أية حزمة."
msgstr[1] "ستزال حزمة واحدة."
msgstr[2] "ستزال حزمتان."
msgstr[3] "ستزال %d حزم."
msgstr[4] "ستزال %d حزمة."
msgstr[5] "ستزال %d حزمة."

#: ../DistUpgrade/DistUpgradeView.py:377
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "لن تثبت أي حزم جديدة."
msgstr[1] "ستثبت حزمة واحدة جديدة."
msgstr[2] "ستثبت حزمتان جديدتان."
msgstr[3] "ستثبت %d حزم جديدة."
msgstr[4] "ستثبت %d حزمة جديدة."
msgstr[5] "ستثبت %d حزمة جديدة."

#: ../DistUpgrade/DistUpgradeView.py:383
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "لن ترقى أي حزم جديدة."
msgstr[1] "سترقى حزمة واحدة جديدة."
msgstr[2] "سترقى حزمتان جديدتان."
msgstr[3] "سترقى %d حزم جديدة."
msgstr[4] "سترقى %d حزمة جديدة."
msgstr[5] "سترقى %d حزمة جديدة."

#: ../DistUpgrade/DistUpgradeView.py:391
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"تحتاج لتنزيل ما مجمله %s. "

#: ../DistUpgrade/DistUpgradeView.py:396
msgid ""
"Installing the upgrade can take several hours. Once the download has "
"finished, the process cannot be canceled."
msgstr ""
"تثبيت الترقية قد يأخذ بضع ساعات. حالما ينتهي التنزيل، فلا يمكن إلغاء العملية."

#: ../DistUpgrade/DistUpgradeView.py:400
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be canceled."
msgstr ""
"جلب وتثبيت الترقية قد يأخذ بضع ساعات. حالما ينتهي التنزيل، لا يمكن إلغاء "
"العملية."

#: ../DistUpgrade/DistUpgradeView.py:405
msgid "Removing the packages can take several hours. "
msgstr "إزالة الحزم قد يأخذ بضع ساعات. "

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:410
msgid "The software on this computer is up to date."
msgstr "البرمجيات على هذا الحاسوب مُحدّثة."

#: ../DistUpgrade/DistUpgradeView.py:411
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr "لا توجد أي ترقيات متوفرة لنظامك. ستلغى الترقية الآن."

#: ../DistUpgrade/DistUpgradeView.py:427
msgid "Reboot required"
msgstr "إعادة التشغيل مطلوبة"

#: ../DistUpgrade/DistUpgradeView.py:428
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr "لقد انتهت الترقية وإعادة التشغيل مطلوبة. هل تود القيام بذلك الآن؟"

#: ../DistUpgrade/DistUpgradeViewText.py:82
#, python-format
msgid "Progress: [%3i%%]"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:141
msgid ""
"Please report this as a bug and include the files /var/log/dist-upgrade/main."
"log and /var/log/dist-upgrade/apt.log in your report. The upgrade has "
"aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"رجاءً أبلغ عن هذا كعلّة وأرفق الملفان /var/log/dist-upgrade/main.log و /var/"
"log/dist-upgrade/apt.log في البلاغ. تم الخروج من الترقية.\n"
"ملف sources.list الأصلي حُفِظَ في /etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewText.py:165
msgid "Aborting"
msgstr "يُجهض"

#: ../DistUpgrade/DistUpgradeViewText.py:171
msgid "Demoted:\n"
msgstr "حطّت رتبته:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:178
msgid "To continue please press [ENTER]"
msgstr "للإستمرار اضغط على [Enter]"

#: ../DistUpgrade/DistUpgradeViewText.py:215
#: ../DistUpgrade/DistUpgradeViewText.py:253
#: ../DistUpgrade/DistUpgradeViewText.py:261
msgid "Continue [yN] "
msgstr "استمر [ن(ل)] "

#: ../DistUpgrade/DistUpgradeViewText.py:215
#: ../DistUpgrade/DistUpgradeViewText.py:253
msgid "Details [d]"
msgstr "التّفاصيل [ف]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:219
#: ../DistUpgrade/DistUpgradeViewText.py:264
msgid "y"
msgstr "ن"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:222
#: ../DistUpgrade/DistUpgradeViewText.py:271
msgid "n"
msgstr "ل"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:225
msgid "d"
msgstr "ف"

#: ../DistUpgrade/DistUpgradeViewText.py:230
#, python-format
msgid "No longer supported: %s\n"
msgstr "لم تعد مدعومة: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:235
#, python-format
msgid "Remove: %s\n"
msgstr "إزالة: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:245
#, python-format
msgid "Install: %s\n"
msgstr "تثبيت: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:250
#, python-format
msgid "Upgrade: %s\n"
msgstr "ترقية: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:268
msgid "Continue [Yn] "
msgstr "تابع [Yn] "

#: ../DistUpgrade/DistUpgradeViewText.py:293
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"لإتمام الترقية تنبغي إعادة تشغيل النظام.\n"
"إن اخترت 'ن' فإن النظام سيعاد تشغيله."

#: ../DistUpgrade/GtkProgress.py:71
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "ينزّل الملف %(current)li من %(total)li بسرعة %(speed)s/ثانية"

#: ../DistUpgrade/GtkProgress.py:77
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "ينزّل الملف %(current)li من %(total)li"

#: ../data/gtkbuilder/AcquireProgress.ui.h:1
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:7
msgid "Show progress of individual files"
msgstr "أظهر تقدّم الملفات المفردة"

#: ../data/gtkbuilder/DistUpgrade.ui.h:1
msgid "_Cancel Upgrade"
msgstr "أ_لغ الترقية"

#: ../data/gtkbuilder/DistUpgrade.ui.h:2
msgid "_Resume Upgrade"
msgstr "أ_كمل التحديث"

#: ../data/gtkbuilder/DistUpgrade.ui.h:3
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>أألغي الترقية الجارية؟</big></b>\n"
"\n"
"إن ألغيت الترقية فقد يبقى نظامك في حالة غير صالحة للاستخدام. نحثك بشدة أن "
"تواصل الترقية."

#: ../data/gtkbuilder/DistUpgrade.ui.h:6
msgid "_Start Upgrade"
msgstr "اب_دأ الترقية"

#: ../data/gtkbuilder/DistUpgrade.ui.h:9
msgid "_Replace"
msgstr "_استبدل"

#: ../data/gtkbuilder/DistUpgrade.ui.h:10
msgid "Difference between the files"
msgstr "الفرق بين الملفات"

#: ../data/gtkbuilder/DistUpgrade.ui.h:11
msgid "_Report Bug"
msgstr "أ_بلغ عن علّة"

#: ../data/gtkbuilder/DistUpgrade.ui.h:12
msgid "_Continue"
msgstr "ا_ستمر"

#: ../data/gtkbuilder/DistUpgrade.ui.h:13
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>أأبدأ الترقية؟</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:15
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>أعد تشغيل النظام لإكمال عملية الترقية</big></b>\n"
"\n"
"من فضلك احفظ أي عمل كنت تقوم به أولا."

#: ../data/gtkbuilder/DistUpgrade.ui.h:18
msgid "Distribution Upgrade"
msgstr "ترقية التوزيعة"

#: ../data/gtkbuilder/DistUpgrade.ui.h:20
#, no-c-format
msgid "<b><big>Upgrading Ubuntu to version %s</big></b>"
msgstr "<b><big>ترقية أوبونتو إلى الإصدارة %s</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:21
msgid "    "
msgstr "    "

#: ../data/gtkbuilder/DistUpgrade.ui.h:23
msgid "Setting new software channels"
msgstr "يضبط قنوات البرمجيات الجديدة"

#: ../data/gtkbuilder/DistUpgrade.ui.h:25
msgid "Restarting the computer"
msgstr "يعيد تشغيل الحاسوب"

#: ../data/gtkbuilder/DistUpgrade.ui.h:28
msgid "Terminal"
msgstr "طرفية"

#: ../data/gtkbuilder/ReleaseNotes.ui.h:2
msgid "_Upgrade"
msgstr "تر_قية"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:1
msgid "<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr "<b>تتوفر إصدارة جديدة من أوبونتو، أترغب في الترقية؟</b>"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:2
msgid "Don't Upgrade"
msgstr "لا أرغب"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:3
msgid "Ask Me Later"
msgstr "اسألني لاحقا"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:4
msgid "Yes, Upgrade Now"
msgstr "نعم، رقِّ الآن"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:5
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "لقد رفضت الترقية إلى أوبونتو الجديدة"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:6
msgid ""
"You can upgrade at a later time by opening Software Updater and click on "
"\"Upgrade\"."
msgstr ""
"يمكنك ترقية الإصدارة في وقت لاحق عن طريق فتح محدث البرمجيات والنقر على \"رق"
"\"."

#: ../data/com.ubuntu.release-upgrader.policy.in.h:1
msgid "Perform a release upgrade"
msgstr "أجر ترقية للإصدارة"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:2
msgid "To upgrade Ubuntu, you need to authenticate."
msgstr "تحتاج للاستيثاق لترقية أوبونتو."

#: ../data/com.ubuntu.release-upgrader.policy.in.h:3
msgid "Perform a partial upgrade"
msgstr "أجر ترقية جزئية"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:4
msgid "To perform a partial upgrade, you need to authenticate."
msgstr "تحتاج للاستيثاق لتنفيذ الترقية الجزئية."

#: ../do-partial-upgrade:75 ../do-release-upgrade:80
msgid "Show version and exit"
msgstr "اعرض الإصدارة واخرج"

#: ../do-partial-upgrade:78 ../do-release-upgrade:87
msgid "Directory that contains the data files"
msgstr "المجلد الذي يحتوي ملفات البيانات"

#: ../do-partial-upgrade:81 ../do-release-upgrade:100
msgid "Run the specified frontend"
msgstr "يشغل الواجهة المحددة"

#: ../do-partial-upgrade:112
msgid "Running partial upgrade"
msgstr "يُجري ترقية جزئية"

#: ../do-release-upgrade:34 ../do-release-upgrade:46
msgid "Downloading the release upgrade tool"
msgstr "ينزّل أداة الترقية"

#: ../do-release-upgrade:83
msgid ""
"If using the latest supported release, upgrade to the development release"
msgstr ""

#: ../do-release-upgrade:90 ../check_new_release_gtk.py:181
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr "حاول الترقية إلى أحدث إصدارة باستخدام المحدِّث من $distro-proposed"

#: ../do-release-upgrade:94
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"يعمل في طور ترقية خاص.\n"
"حاليا الطوران المدعومان هما 'desktop' للترقية الاعتيادية لنظام سطح مكتب، و "
"'server' لنظم الخواديم."

#: ../do-release-upgrade:103
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""
"تحقق فقط إذا كان هناك إصدار جديد من التوزيعة متوفرا و أرسل تقريرا خلال كود "
"الخروج"

#: ../do-release-upgrade:108
msgid ""
"Try the upgrade with third party mirrors and repositories enabled instead of "
"commenting them out."
msgstr ""

#: ../do-release-upgrade:122
msgid "The options --devel-release and --proposed are"
msgstr ""

#: ../do-release-upgrade:123
msgid "mutually exclusive. Please use only one of them."
msgstr "متنافيين. يرجى استخدام واحد فقط منهم."

#: ../do-release-upgrade:127
msgid "Checking for a new Ubuntu release"
msgstr "يتحقق من وجود إصدارة جديدة من أبونتو"

#: ../do-release-upgrade:139
msgid "Your Ubuntu release is not supported anymore."
msgstr "نسختك من أبونتو لم تعد مدعومة بعد الآن."

#: ../do-release-upgrade:140
msgid ""
"For upgrade information, please visit:\n"
"%(url)s\n"
msgstr ""
"لمعلومات عن الترقية، رجاءً قم بزيارة:\n"
"%(url)s\n"

#: ../do-release-upgrade:147
msgid "In /etc/update-manager/release-upgrades Prompt "
msgstr ""

#: ../do-release-upgrade:148
msgid "is set to never so upgrading is not possible."
msgstr ""

#: ../do-release-upgrade:150
msgid "There is no development version of an LTS available."
msgstr ""

#: ../do-release-upgrade:151
msgid "To upgrade to the latest non-LTS development release "
msgstr ""

#: ../do-release-upgrade:152
msgid "set Prompt=normal in /etc/update-manager/release-upgrades."
msgstr ""

#: ../do-release-upgrade:154
msgid "Upgrades to the development release are only "
msgstr ""

#: ../do-release-upgrade:155
msgid "available from the latest supported release."
msgstr ""

#: ../do-release-upgrade:157
msgid "No new release found."
msgstr ""

#: ../do-release-upgrade:162
msgid "Release upgrade not possible right now"
msgstr "يتعذّر ترقية الإصدارة حاليا"

#: ../do-release-upgrade:163
#, c-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr "تعذّر ترفية الإصدارة حاليا، أعد المحاولة لاحقا. رد الخادوم: '%s'"

#: ../do-release-upgrade:169
#, c-format
msgid "New release '%s' available."
msgstr "لا تتوفر إصدارات '%s'"

#: ../do-release-upgrade:170
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "شغّل 'do-release-upgrade' للترقية إليه."

#: ../do-release-upgrade:187
msgid "Please install all available updates for your release before upgrading."
msgstr ""

#: ../do-release-upgrade:203
msgid ""
"You have not rebooted after updating a package which requires a reboot. "
"Please reboot before upgrading."
msgstr ""

#: ../check_new_release_gtk.py:85
msgid "Software Updater"
msgstr "محدّث البرمجيات"

#: ../check_new_release_gtk.py:113
#, python-format
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "يتوفر ترقية إلى أوبونتو %(version)s"

#. print("don't upgrade")
#: ../check_new_release_gtk.py:144
#, python-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "لقد رفضت الترقية إلى أوبونتو %s"

#: ../check_new_release_gtk.py:177
msgid "Check if upgrading to the latest devel release is possible"
msgstr "يتحقق إن كانت الترقية ممكنة إلى أحدث إصدارة تطوير"

#: ../check_new_release_gtk.py:186
msgid "Add debug output"
msgstr "أضف مُخرَجات التنقيح"

#~ msgid ""
#~ "An unresolvable problem occurred while calculating the upgrade:\n"
#~ "%s\n"
#~ "\n"
#~ " This can be caused by:\n"
#~ " * Upgrading to a pre-release version of Ubuntu\n"
#~ " * Running the current pre-release version of Ubuntu\n"
#~ " * Unofficial software packages not provided by Ubuntu\n"
#~ "\n"
#~ msgstr ""
#~ "صودفت مشكلة غير قابلة للحل أثناء إحصاء الترقية:\n"
#~ "%s\n"
#~ "\n"
#~ " قد يكون هذا ناتج عن:\n"
#~ " * الترقية إلى نسخة ما قبل الإصدار من أبونتو\n"
#~ " * تشغيل نسخة ما قبل الإصدار الحالية من أبونتو\n"
#~ " * حزم برمجيات غير رسمية ليست مقدمة من أبونتو\n"
#~ "\n"

#~ msgid ""
#~ "Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
#~ "desktop or edubuntu-desktop package and it was not possible to detect "
#~ "which version of Ubuntu you are running.\n"
#~ " Please install one of the packages above first using synaptic or apt-get "
#~ "before proceeding."
#~ msgstr ""
#~ "نظامك لا يحتوي أيا من الحزم ubuntu-desktop أو kubuntu-desktop أو xubuntu-"
#~ "desktop أو edubuntu-desktop و لم يمكن الكشف عن نسخة أوبونتو التي "
#~ "تستعملها.\n"
#~ " رجاءً ثبت إحدى الحزم المذكورة أعلاه باستخدام synaptic أو apt-get قبل "
#~ "المواصلة."

#~ msgid "Sandbox setup failed"
#~ msgstr "فشل إعداد صندوق الرمل"

#~ msgid "It was not possible to create the sandbox environment."
#~ msgstr "تعذّر إنشاء بيئة محاطة (صندوق رمل)"

#~ msgid "Sandbox mode"
#~ msgstr "طور صندوق الرمل"

#~ msgid ""
#~ "This upgrade is running in sandbox (test) mode. All changes are written "
#~ "to '%s' and will be lost on the next reboot.\n"
#~ "\n"
#~ "*No* changes written to a system directory from now until the next reboot "
#~ "are permanent."
#~ msgstr ""
#~ "هذه الترقية تعمل في نمط المرملة (الاختبار). جميع التغييرات تُكتب إلى '%s' "
#~ "وستُفقد عند إعادة التشغيل التالي.\n"
#~ "\n"
#~ "*لن* تُكتب أي تغييرات إلى مجلد النظام من الآن حتى إعادة التشغيل التالي."

#~ msgid ""
#~ "Your python install is corrupted. Please fix the '/usr/bin/python' "
#~ "symlink."
#~ msgstr ""
#~ "تثبيتة python الحالية معطوبة. رجاءً أصلح الرابط الرمزي '/usr/bin/python'."

#~ msgid "Package 'debsig-verify' is installed"
#~ msgstr "حزمة 'debsig-verify' مثبتة"

#~ msgid ""
#~ "The upgrade can not continue with that package installed.\n"
#~ "Please remove it with synaptic or 'apt-get remove debsig-verify' first "
#~ "and run the upgrade again."
#~ msgstr ""
#~ "لا يمكن مواصة الترقية و تلك الحزمة مثبّتة.\n"
#~ "أزلها باستخدام synaptic أو 'apt-get' ثم أجر الترقية مجددا."

#~ msgid ""
#~ "The upgrade has aborted. The upgrade needs a total of %s free space on "
#~ "disk '%s'. Please free at least an additional %s of disk space on '%s'. "
#~ "Empty your trash and remove temporary packages of former installations "
#~ "using 'sudo apt-get clean'."
#~ msgstr ""
#~ "لقد أُجهضت الترقية. تحتاج الترقية إلى %s مساحة خالية على القرص '%s'. من "
#~ "فضلك أفرغ %s على الأقل من مساحة القرص '%s'. أفرغ المهملات وأزل الحزم "
#~ "المؤقتة من التثبيتات السابقة باستخدام 'sudo apt-get clean'."

#~ msgid "evms in use"
#~ msgstr "evms قيد الاستخدام"

#~ msgid ""
#~ "Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
#~ "software is no longer supported, please switch it off and run the upgrade "
#~ "again when this is done."
#~ msgstr ""
#~ "يستخدم نظامك مدير الصوت 'evms' في /proc/mounts. برمجيات 'evms' لم تعد "
#~ "مدعومة، من فضلك أغلقه ونفذ الترقية مجددا عندما ينتهي."

#~ msgid ""
#~ "This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
#~ "version of this driver is available that works with your video card in "
#~ "Ubuntu 10.04 LTS.\n"
#~ "\n"
#~ "Do you want to continue?"
#~ msgstr ""
#~ "يستخدم حاسوبك حاليا مشغل 'nvidia' لرسوميات NVIDIA. لا توجد نسخة من هذا "
#~ "المشغل متوافقة مع عتادك في أوبونتو 10.04 LTS.\n"
#~ "\n"
#~ "أتريد المواصلة؟"

#~ msgid "No i686 CPU"
#~ msgstr "لا يوجد معالج i686"

#~ msgid ""
#~ "Your system uses an i586 CPU or a CPU that does not have the 'cmov' "
#~ "extension. All packages were built with optimizations requiring i686 as "
#~ "the minimal architecture. It is not possible to upgrade your system to a "
#~ "new Ubuntu release with this hardware."
#~ msgstr ""
#~ "نظامك يستخدم وحدة معالجة مركزية من طراز i586 لا تملك ملحق cmov. تم بناء "
#~ "كل الحزم متطلبةً لبنية i686 كحد أدنى. ليس من الممكن ترقية نظامك إلى إصدارة "
#~ "أوبونتو الجديدة مع هذا العتاد."

#~ msgid "Sandbox upgrade using aufs"
#~ msgstr "ترقية في بيئة محكومة (صندوق رمل)"

#~ msgid "Test upgrade with a sandbox aufs overlay"
#~ msgstr "اختبر الترقية في بيئة محكومة (صندوق رمل)"

#~ msgid "No new release found"
#~ msgstr "لا توجد إصدارات أحدث"

#~ msgid "Authentication is required to perform a partial upgrade"
#~ msgstr "الاستيثاق مطلوب لإجراء ترقية جزئية"

#~ msgid "Authentication is required to perform a release upgrade"
#~ msgstr "الاستيثاق مطلوب لترقية الإصدارة"

#~ msgid ""
#~ "If none of this applies, then please report this bug using the command "
#~ "'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
#~ msgstr ""
#~ "إذا لم يكن أي من هذه مفيدًا، رجاءً أبلغ عن هذه العلة باستخدام الأمر 'ubuntu-"
#~ "bug ubuntu-release-upgrader-core' في طرفية."

#~ msgid "Your graphics hardware may not be fully supported in Ubuntu 13.04."
#~ msgstr ""
#~ "قد يكون عتاد الرسوميات في جهازك ليس مدعوما بالكامل في أوبونتو 13.04."

#~ msgid "<b><big>Upgrading Ubuntu to version 13.04</big></b>"
#~ msgstr "<b><big>ترقية أوبونتو إلى الإصدارة 13.04</big></b>"

#~ msgid ""
#~ "While scanning your repository information no mirror entry for the "
#~ "upgrade was found. This can happen if you run a internal mirror or if the "
#~ "mirror information is out of date.\n"
#~ "\n"
#~ "Do you want to rewrite your 'sources.list' file anyway? If you choose "
#~ "'Yes' here it will update all '%s' to '%s' entries.\n"
#~ "If you select 'No' the upgrade will cancel."
#~ msgstr ""
#~ "تعذر إيجاد رابط بديل للترقية أثناء البحث في معلومات المستودعات في حاسوبك. "
#~ "قد يحدث هذا إن استخدمت رابط بديل داخلي أو إن كانت معلومات الرابط البديل "
#~ "قديمة.\n"
#~ "\n"
#~ "هل تود التعديل على ملف 'sources.list' لديك على أية حال؟ إذا أجبت ﺑـ'نعم' "
#~ "فستُحدّث كل '%s' إلى '%s'. وإن أجبت ﺑـ'ﻻ' فستُلغى عملية الترقية."

#~ msgid ""
#~ "An unresolvable problem occurred while calculating the upgrade.\n"
#~ "\n"
#~ " This can be caused by:\n"
#~ " * Upgrading to a pre-release version of Ubuntu\n"
#~ " * Running the current pre-release version of Ubuntu\n"
#~ " * Unofficial software packages not provided by Ubuntu\n"
#~ "\n"
#~ msgstr ""
#~ "طرأت مشكلة لا يمكن حلها أثناء حساب الترقية.\n"
#~ "\n"
#~ " هذا يمكن أن يحدث بسبب:\n"
#~ " * الترقية إلى إصدار تجريبي من أوبونتو\n"
#~ " * استخدام الإصدار التجريبي الحالي من أوبونتو\n"
#~ " * حزم برمجيات غير رسمية لا تقدمها أوبونتو\n"
#~ "\n"
