# Polish translation of Update Manager.
# This file is distributed under the same license as the update-manager package.
# Copyright (c) 2006 Sebastian Heinlein
#               2007 Canonical
# Polish translation by:
# Zygmunt Krynicki <zkrynicki@gmail.com>, 2005-2006
# Tomasz Dominikowski <dominikowski@gmail.com>, 2006-2008
# Wiktor Wandachowicz <siryes@gmail.com>, 2008
#
# Nazewnictwo i spójność tłumaczeń programów apt, aptitude, synaptic i innych:
# http://wiki.debian.org/PolishL10N/PackageInstallers
#: ../DistUpgrade/DistUpgradeController.py:1075
msgid ""
msgstr ""
"Project-Id-Version: update-manager 0.87\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2021-05-13 16:32-0700\n"
"PO-Revision-Date: 2019-06-18 17:54+0000\n"
"Last-Translator: GTriderXC <gtriderxc@yahoo.com>\n"
"Language-Team: Polish <ubuntu-pl-l10n@lists.ubuntu.com>\n"
"Language: pl\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 "
"|| n%100>=20) ? 1 : 2;\n"
"X-Launchpad-Export-Date: 2019-11-15 04:48+0000\n"
"X-Generator: Launchpad (build c597c3229eb023b1e626162d5947141bf7befb13)\n"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:215 ../DistUpgrade/distro.py:446
#, python-format
msgid "Server for %s"
msgstr "Serwer dla kraju %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:233 ../DistUpgrade/distro.py:239
#: ../DistUpgrade/distro.py:255
msgid "Main server"
msgstr "Główny serwer"

#: ../DistUpgrade/distro.py:259
msgid "Custom servers"
msgstr "Inne serwery"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:151
msgid "Could not calculate sources.list entry"
msgstr "Nie można obliczyć wpisu w sources.list"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:260
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""
"Nie można odnaleźć żadnych plików z pakietami. Może nie jest to płyta z "
"Ubuntu lub architektura komputera jest nieprawidłowa?"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:310
msgid "Failed to add the CD"
msgstr "Nie udało się dodać płyty CD"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:311
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"Wystąpił błąd podczas dodawania płyty CD. Aktualizacja systemu zostanie "
"przerwana. Proszę zgłosić to jako błąd, jeśli jest to oficjalna płyta "
"Ubuntu.\n"
"\n"
"Komunikat błędu jest następujący:\n"
"„%s”"

#: ../DistUpgrade/DistUpgradeCache.py:182
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Usuwanie uszkodzonego pakietu"
msgstr[1] "Usuwanie uszkodzonych pakietów"
msgstr[2] "Usuwanie uszkodzonych pakietów"

#: ../DistUpgrade/DistUpgradeCache.py:185
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"Pakiet \"%s\" znajduje się w niezgodnym stanie i musi zostać zainstalowany "
"ponownie, ale nie odnaleziono żadnego archiwum tego pakietu. Usunąć pakiet "
"teraz aby kontynuować?"
msgstr[1] ""
"Pakiety \"%s\" znajdują się w niezgodnym stanie i muszą zostać zainstalowane "
"ponownie, ale nie odnaleziono żadnego archiwum tych pakietów. Usunąć pakiety "
"teraz aby kontynuować?"
msgstr[2] ""
"Pakiety \"%s\" znajdują się w niezgodnym stanie i muszą zostać zainstalowane "
"ponownie, ale nie odnaleziono żadnego archiwum tych pakietów. Usunąć pakiety "
"teraz aby kontynuować?"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:301
msgid "The server may be overloaded"
msgstr "Serwer może być przeciążony"

#: ../DistUpgrade/DistUpgradeCache.py:414
msgid "Broken packages"
msgstr "Uszkodzone pakiety"

#: ../DistUpgrade/DistUpgradeCache.py:415
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"System zawiera uszkodzone pakiety, które nie mogły zostać naprawione. Przed "
"kontynuowaniem należy je naprawić używając programu Synaptic lub apt-get."

#: ../DistUpgrade/DistUpgradeCache.py:660
#, fuzzy, python-format
msgid "Broken packages after upgrade: %s"
msgstr "Uszkodzone pakiety"

#. the most likely problem is the 3rd party pkgs so don't address
#. foreignPkgs and devRelease being True
#: ../DistUpgrade/DistUpgradeCache.py:669
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
" "
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:672
msgid ""
"This was likely caused by:\n"
" * Unofficial software packages not provided by Ubuntu\n"
"Please use the tool 'ppa-purge' from the ppa-purge \n"
"package to remove software from a Launchpad PPA and \n"
"try the upgrade again.\n"
"\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:680
msgid ""
"This was caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
"This is most likely a transient problem, \n"
"please try again later.\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:687
msgid "This is most likely a transient problem, please try again later."
msgstr "Wystąpiły przejściowe trudności. Proszę spróbować później."

#: ../DistUpgrade/DistUpgradeCache.py:690
msgid ""
"If none of this applies, then please report this bug using the command "
"'ubuntu-bug ubuntu-release-upgrader-core' in a terminal. "
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:692
msgid ""
"If you want to investigate this yourself the log files in '/var/log/dist-"
"upgrade' will contain details about the upgrade. Specifically, look at 'main."
"log' and 'apt.log'."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:698
msgid "Could not calculate the upgrade"
msgstr "Nie można przetworzyć aktualizacji"

#: ../DistUpgrade/DistUpgradeCache.py:757
msgid "Error authenticating some packages"
msgstr "Błąd uwierzytelenienia pakietów"

#: ../DistUpgrade/DistUpgradeCache.py:758
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"Uwierzytelnienie niektórych pakietów nie było możliwe. Może to oznaczać "
"chwilowy błąd sieci. Można spróbować ponownie później. Poniżej znajduje się "
"lista nieuwierzytelnionych pakietów."

#: ../DistUpgrade/DistUpgradeCache.py:779
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""
"Pakiet \"%s\" jest oznaczony do usunięcia, lecz znajduje się na liście "
"pakietów, których nie należy usuwać."

#: ../DistUpgrade/DistUpgradeCache.py:785
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "Niezbędny pakiet \"%s\" jest oznaczony do usunięcia."

#: ../DistUpgrade/DistUpgradeCache.py:794
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr ""
"Próbowanie zainstalowania wersji „%s”, znajdującej się na czarnej liście"

#: ../DistUpgrade/DistUpgradeCache.py:916
#, python-format
msgid "Can't install '%s'"
msgstr "Nie można zainstalować „%s”"

#: ../DistUpgrade/DistUpgradeCache.py:917
msgid ""
"It was impossible to install a required package. Please report this as a bug "
"using 'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
msgstr ""
"Zainstalowanie wymaganego pakietu było niemożliwe. Proszę zgłosić ten błąd "
"wprowadzając w terminalu polecenie „ubuntu-bug ubuntu-release-upgrader-core”."

#: ../DistUpgrade/DistUpgradeCache.py:928
msgid "Can't guess meta-package"
msgstr "Nie można określić meta-pakietu"

#: ../DistUpgrade/DistUpgradeCache.py:929
#, python-format
msgid ""
"Your system does not contain a %s or %s package and it was not possible to "
"detect which version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"Nie masz zainstalowanych pakietów %s lub %s i nie udało się określić jakiej "
"wersji Ubuntu używasz.\n"
" Zainstaluj najpierw wymienione pakiety używając Synaptica lub komendy apt-"
"get."

#: ../DistUpgrade/DistUpgradeController.py:113
msgid "Reading cache"
msgstr "Odczytywanie pamięci podręcznej"

#: ../DistUpgrade/DistUpgradeController.py:225
msgid "Unable to get exclusive lock"
msgstr "Nie można uzyskać blokady na wyłączność"

#: ../DistUpgrade/DistUpgradeController.py:226
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"Zazwyczaj oznacza to, że uruchomiony jest inny program zarządzający "
"pakietami (jak apt-get lub aptitude). Należy najpierw zakończyć działanie "
"tego programu."

#: ../DistUpgrade/DistUpgradeController.py:284
msgid "Upgrading over remote connection not supported"
msgstr "Aktualizacja za pośrednictwem połączenia zdalnego nie jest obsługiwana"

#: ../DistUpgrade/DistUpgradeController.py:285
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"Uruchomiono aktualizację za pośrednictwem zdalnego połączenia ssh, przy "
"użyciu interfejsu, który nie obsługuje takiego połączenia. Proszę spróbować "
"aktualizacji w trybie tekstowym z opcją „do-release-upgrade”.\n"
"\n"
"Aktualizacja zostanie przerwana. Proszę spróbować ponownie z pominięciem "
"połączenia ssh."

#: ../DistUpgrade/DistUpgradeController.py:299
msgid "Continue running under SSH?"
msgstr "Kontynuować połączenie SSH?"

#: ../DistUpgrade/DistUpgradeController.py:300
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"Uruchomiona sesja działa z pod kontrolą ssh. Obecnie nie zaleca się "
"dokonywania uaktualnień za pośrednictwem ssh, ponieważ w przypadku błędu "
"przywracanie systemu może być trudniejsze.\n"
"\n"
"W przypadku kontynuowania, uruchomiony zostanie dodatkowy demon ssh na "
"porcie „%s”.\n"
"Kontynuować?"

#: ../DistUpgrade/DistUpgradeController.py:314
msgid "Starting additional sshd"
msgstr "Uruchamianie dodatkowego demona sshd"

#: ../DistUpgrade/DistUpgradeController.py:315
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"Dodatkowy demon sshd zostanie uruchomiony na porcie '%s', aby ułatwić "
"odzyskiwanie w razie problemów z bieżącą usługą ssh. W przypadku "
"niepowodzenia z aktualną sesją ssh, wciąż można podłączyć się do sesji "
"dodatkowej.\n"

#: ../DistUpgrade/DistUpgradeController.py:323
#, python-format
msgid ""
"If you run a firewall, you may need to temporarily open this port. As this "
"is potentially dangerous it's not done automatically. You can open the port "
"with e.g.:\n"
"'%s'"
msgstr ""
"Jeśli używana jest zapora firewall, może okazać się konieczne tymczasowe "
"otwarcie tego portu. Czynność ta jest potencjalnie niebezpieczna, dlatego "
"nie zostanie wykonana automatycznie. Port może zostać otwarty między innymi "
"za pomocą:\n"
"'%s'"

#: ../DistUpgrade/DistUpgradeController.py:401
#: ../DistUpgrade/DistUpgradeController.py:425
msgid "Can not upgrade"
msgstr "Nie można zaktualizować"

#: ../DistUpgrade/DistUpgradeController.py:402
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr ""
"Aktualizacja z wersji \\\"%s\\\" do \\\"%s\\\" nie jest możliwa przy użyciu "
"tego narzędzia."

#: ../DistUpgrade/DistUpgradeController.py:426
msgid ""
"Your python3 install is corrupted. Please fix the '/usr/bin/python3' symlink."
msgstr ""
"Twoja instalacja python3 jest uszkodzona. Napraw dowiązanie symboliczne '/"
"usr/bin/python3'."

#: ../DistUpgrade/DistUpgradeController.py:455
#, python-format
msgid "Can not write to '%s'"
msgstr "Nie można zapisać do „%s”"

#: ../DistUpgrade/DistUpgradeController.py:456
#, python-format
msgid ""
"Its not possible to write to the system directory '%s' on your system. The "
"upgrade can not continue.\n"
"Please make sure that the system directory is writable."
msgstr ""
"Zapisywanie do katalogu systemowego „%s” nie jest możliwe. Aktualizacja "
"zostanie przerwana.\n"
"Aby spróbować ponownie, należy upewnić się, że dokonywanie zmian w katalogu "
"systemu jest możliwe."

#: ../DistUpgrade/DistUpgradeController.py:467
msgid "Include latest updates from the Internet?"
msgstr "Dołączyć najnowsze aktualizacje z Internetu?"

#: ../DistUpgrade/DistUpgradeController.py:468
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""
"System aktualizacji może połączyć się z internetem, aby automatycznie pobrać "
"i zainstalować najnowsze aktualizacje. Jeśli masz połączenie sieciowe, jest "
"to opcja zalecana.\n"
"\n"
"Aktualizacja zabierze trochę czasu, ale gdy zostanie zakończona, system "
"będzie w pełni aktualny. Można tego zaniechać, jednak zalecana jest "
"instalacja najnowszych aktualizacji.\n"
"Jeśli teraz odpowiesz \"NIE\", sieć nie zostanie użyta."

#: ../DistUpgrade/DistUpgradeController.py:646
#, python-format
msgid "Not for humans during development stage of release %s"
msgstr "Nie dla ludzi podczas rozwoju wydania %s"

#: ../DistUpgrade/DistUpgradeController.py:747
#, python-format
msgid "disabled on upgrade to %s"
msgstr "wyłączony podczas aktualizacji do %s"

#: ../DistUpgrade/DistUpgradeController.py:806
msgid "No valid sources.list entry found"
msgstr "Nie znaleziono prawidłowego wpisu w sources.list"

#: ../DistUpgrade/DistUpgradeController.py:807
#, python-format
msgid ""
"While scanning your repository information no entry about %s could be "
"found.\n"
"\n"
"An upgrade might not succeed.\n"
"\n"
"Do you want to continue anyway?"
msgstr ""
"Podczas skanowania informacji repozytorium nie znaleziono wpisu o %s .\n"
"\n"
"Aktualizacja może się nie powieść.\n"
"\n"
"Czy mimo to chcesz kontynuować?"

#: ../DistUpgrade/DistUpgradeController.py:817
msgid "No valid mirror found"
msgstr "Nie odnaleziono poprawnego serwera lustrzanego"

#: ../DistUpgrade/DistUpgradeController.py:818
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run an internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"Podczas skanowania informacji o repozytoriach nie znaleziono mirrora do "
"aktualizacji. Może się to zdarzyć, jeśli uruchamiasz wewnętrzny mirror lub "
"informacje w mirrorze są nieaktualne.\n"
"\n"
"Czy chcesz mimo to nadpisać plik \"sources.list\"? Jeśli wybierzesz \"Tak\" "
"wszystkie wpisy \"%s\" zostaną zmienione na \"%s\".\n"
"Jeśli wybierzesz \"Nie\", aktualizacja zostanie anulowana."

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:838
msgid "Generate default sources?"
msgstr "Wygenerować domyślne źródła?"

#: ../DistUpgrade/DistUpgradeController.py:839
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"Podczas przetwarzania informacji o repozytoriach nie odnaleziono poprawnego "
"wpisu dla \"%s\".\n"
"\n"
"Dodać domyślne wpisy dla \"%s\"? Wybranie \"Nie\" przerwie aktualizację."

#: ../DistUpgrade/DistUpgradeController.py:874
#: ../DistUpgrade/DistUpgradeController.py:880
msgid "Repository information invalid"
msgstr "Błędne informacje o repozytoriach"

#: ../DistUpgrade/DistUpgradeController.py:875
msgid ""
"Upgrading the repository information resulted in a invalid file so a bug "
"reporting process is being started."
msgstr ""
"W wyniku uaktualnienia informacji o repozytoriach, uzyskano nieprawidłowy "
"plik. Uruchomiono proces zgłaszania błędów."

#: ../DistUpgrade/DistUpgradeController.py:881
msgid ""
"Upgrading the repository information resulted in a invalid file. To report a "
"bug install apport and then execute 'apport-bug ubuntu-release-upgrader'."
msgstr ""
"Uaktualnienia informacji o repozytoriach zaowocowało nieprawidłowym plikiem. "
"Aby zgłosić błąd zainstaluj apport a następnie wykonaj  'apport-bug ubuntu-"
"release-upgrader'."

#: ../DistUpgrade/DistUpgradeController.py:890
msgid "Third party sources disabled"
msgstr "Źródła niezależnych dostawców zostały wyłączone"

#: ../DistUpgrade/DistUpgradeController.py:891
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"Niektóre wpisy niezależnych dostawców w pliku \"sources.list\" zostały "
"wyłączone. Można ponownie je włączyć po aktualizacji używając narzędzia "
"\"software-properties\" lub programu Synaptic."

#: ../DistUpgrade/DistUpgradeController.py:933
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "Pakiet w niezgodnym stanie"
msgstr[1] "Pakiety w niezgodnym stanie"
msgstr[2] "Pakiety w niezgodnym stanie"

#: ../DistUpgrade/DistUpgradeController.py:936
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"Pakiet \"%s\" znajduje się w niezgodnym stanie i musi zostać zainstalowany "
"ponownie, ale nie odnaleziono żadnego archiwum tego pakietu. Proszę "
"zainstalować pakiet ręcznie lub usunąć go z systemu."
msgstr[1] ""
"Pakiety \"%s\" znajdują się w niezgodnym stanie i muszą zostać zainstalowane "
"ponownie, ale nie odnaleziono żadnego archiwum tych pakietów. Proszę "
"zainstalować pakiety ręcznie lub usunąć je z systemu."
msgstr[2] ""
"Pakiety \"%s\" znajdują się w niezgodnym stanie i muszą zostać zainstalowane "
"ponownie, ale nie odnaleziono żadnego archiwum tych pakietów. Proszę "
"zainstalować pakiety ręcznie lub usunąć je z systemu."

#: ../DistUpgrade/DistUpgradeController.py:999
msgid "Error during update"
msgstr "Błąd podczas aktualizacji"

#: ../DistUpgrade/DistUpgradeController.py:1000
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"Wystąpił problem podczas aktualizacji. Zazwyczaj wynika to z problemów z "
"siecią, proszę sprawdzić połączenie sieciowe i spróbować ponownie."

#: ../DistUpgrade/DistUpgradeController.py:1043
#: ../DistUpgrade/DistUpgradeController.py:1048
msgid "EFI System Partition (ESP) not usable"
msgstr "Nie można użyć partycji systemowej EFI (ESP)"

#: ../DistUpgrade/DistUpgradeController.py:1044
msgid ""
"Your EFI System Partition (ESP) is not mounted at /boot/efi. Please ensure "
"that it is properly configured and try again."
msgstr ""
"Partycja systemowa EFI (ESP) nie jest zamontowana w /boot/efi. Upewnij się, "
"że jest odpowiednio skonfigurowana i spróbuj ponownie."

#: ../DistUpgrade/DistUpgradeController.py:1049
msgid ""
"The EFI System Partition (ESP) mounted at /boot/efi is not writable. Please "
"mount this partition read-write and try again."
msgstr ""
"Partycja systemowa EFI (ESP) zamontowana w /boot/efi nie ma możliwości "
"zapisu. Zamontuj ją z uprawnieniami odczytu oraz zapisu i spróbuj ponownie."

#: ../DistUpgrade/DistUpgradeController.py:1056
msgid "Not enough free disk space"
msgstr "Zbyt mało miejsca na dysku"

#. TRANSLATORS: you can change the order of the sentence,
#. make sure to keep all {str_*} string untranslated.
#: ../DistUpgrade/DistUpgradeController.py:1059
#, python-brace-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of {str_total} free space "
"on disk '{str_dir}'. Please free at least an additional {str_needed} of disk "
"space on '{str_dir}'. {str_remedy}"
msgstr ""

#. specific ways to resolve lack of free space
#: ../DistUpgrade/DistUpgradeController.py:1064
msgid ""
"Remove temporary packages of former installations using 'sudo apt clean'."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1066
msgid ""
"You can remove old kernels using 'sudo apt autoremove' and you could also "
"set COMPRESS=xz in /etc/initramfs-tools/initramfs.conf to reduce the size of "
"your initramfs."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1071
msgid ""
"Empty your trash and remove temporary packages of former installations using "
"'sudo apt-get clean'."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1074
msgid "Reboot to clean up files in /tmp."
msgstr ""

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:1113
#: ../DistUpgrade/DistUpgradeController.py:1998
#: ../DistUpgrade/DistUpgradeController.py:2050
msgid "Calculating the changes"
msgstr "Przetwarzanie zmian"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:1157
msgid "Do you want to start the upgrade?"
msgstr "Rozpocząć aktualizację?"

#: ../DistUpgrade/DistUpgradeController.py:1176
#, python-format
msgid ""
"Livepatch security updates are not available for Ubuntu %s. If you upgrade, "
"Livepatch will turn off."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1248
msgid "Upgrade canceled"
msgstr "Aktualizacja anulowana"

#: ../DistUpgrade/DistUpgradeController.py:1249
msgid ""
"The upgrade will cancel now and the original system state will be restored. "
"You can resume the upgrade at a later time."
msgstr ""
"Aktualizacja zostanie teraz anulowana, a system przywrócony do pierwotnego "
"stanu. W późniejszym czasie można ponowić próbę aktualizacji wydania."

#: ../DistUpgrade/DistUpgradeController.py:1255
#: ../DistUpgrade/DistUpgradeController.py:1400
msgid "Could not download the upgrades"
msgstr "Pobranie aktualizacji było niemożliwe"

#: ../DistUpgrade/DistUpgradeController.py:1256
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far have been kept."
msgstr ""
"Proces aktualizacji został przerwany. Proszę sprawdzić stan połączenia "
"sieciowego lub nośników instalacyjnych i spróbować ponownie. Wszystkie "
"dotychczas pobrane pliki zostały zachowane."

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1349
#: ../DistUpgrade/DistUpgradeController.py:1388
#: ../DistUpgrade/DistUpgradeController.py:1504
msgid "Error during commit"
msgstr "Błąd podczas zatwierdzania"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1351
#: ../DistUpgrade/DistUpgradeController.py:1390
#: ../DistUpgrade/DistUpgradeController.py:1551
msgid "Restoring original system state"
msgstr "Przywracanie pierwotnego stanu systemu"

#: ../DistUpgrade/DistUpgradeController.py:1352
#: ../DistUpgrade/DistUpgradeController.py:1367
#: ../DistUpgrade/DistUpgradeController.py:1391
msgid "Could not install the upgrades"
msgstr "Nie można zainstalować aktualizacji"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1357
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"Aktualizacja została przerwana. System może znajdować się w stanie "
"nienadającym się do użytku. Zostanie teraz uruchomione odzyskiwanie (dpkg --"
"configure -a)."

#: ../DistUpgrade/DistUpgradeController.py:1362
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug in a browser at http://bugs.launchpad.net/ubuntu/"
"+source/ubuntu-release-upgrader/+filebug and attach the files in /var/log/"
"dist-upgrade/ to the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"Proszę zgłosić ten błąd poprzez przeglądarkę internetową, pod adresem: "
"http://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+filebug "
"and attach the files in /var/log/dist-upgrade/\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1401
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"Aktualizacja została przerwana. Proszę sprawdzić połączenie internetowe lub "
"nośnik instalacyjny i spróbować ponownie. "

#: ../DistUpgrade/DistUpgradeController.py:1429
msgid "Searching for obsolete software"
msgstr "Wyszukiwanie przestarzałego oprogramowania"

#: ../DistUpgrade/DistUpgradeController.py:1492
msgid "Remove obsolete packages?"
msgstr "Usunąć przestarzałe pakiety?"

#: ../DistUpgrade/DistUpgradeController.py:1493
#: ../data/gtkbuilder/DistUpgrade.ui.h:8
msgid "_Keep"
msgstr "_Zachowaj"

#: ../DistUpgrade/DistUpgradeController.py:1493
msgid "_Remove"
msgstr "_Usuń"

#: ../DistUpgrade/DistUpgradeController.py:1505
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr "Wystąpił problem podczas czyszczenia. Więcej informacji poniżej. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1589
msgid "Required depends is not installed"
msgstr "Wymagana zależność nie jest zainstalowana."

#: ../DistUpgrade/DistUpgradeController.py:1590
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "Wymagana zależność \"%s\" nie jest zainstalowana. "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1857
#: ../DistUpgrade/DistUpgradeController.py:1948
msgid "Checking package manager"
msgstr "Sprawdzanie menedżera pakietów"

#: ../DistUpgrade/DistUpgradeController.py:1863
#: ../DistUpgrade/DistUpgradeController.py:1869
msgid "Preparing the upgrade failed"
msgstr "Przygotowanie aktualizacji nie powiodło się"

#: ../DistUpgrade/DistUpgradeController.py:1864
msgid ""
"Preparing the system for the upgrade failed so a bug reporting process is "
"being started."
msgstr ""
"Przygotowanie systemu do aktualizacji nie powiodło się. Zostanie uruchomiony "
"proces raportowania błędów."

#: ../DistUpgrade/DistUpgradeController.py:1870
msgid ""
"Preparing the system for the upgrade failed. To report a bug install apport "
"and then execute 'apport-bug ubuntu-release-upgrader'."
msgstr ""
"Nie udało się przygotować systemu do uaktualnienia. Aby zgłosić błąd, proszę "
"zainstalować program apport i wykonać polecenie „apport-bug ubuntu-release-"
"upgrader”."

#: ../DistUpgrade/DistUpgradeController.py:1887
#: ../DistUpgrade/DistUpgradeController.py:1897
msgid "Getting upgrade prerequisites failed"
msgstr "Pobranie elementów wymaganych do aktualizacji nie powiodło się"

#: ../DistUpgrade/DistUpgradeController.py:1888
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Additionally, a bug reporting process is being started."
msgstr ""
"Nie odnaleziono wszystkich potrzebnych informacji do aktualizacji systemu. "
"Proces zostanie przerwany, a system powróci do pierwotnego stanu.\n"
"\n"
"Następnie uruchomiony zostanie proces raportowania błędów."

#: ../DistUpgrade/DistUpgradeController.py:1898
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"To report a bug install apport and then execute 'apport-bug ubuntu-release-"
"upgrader'."
msgstr ""
"System nie jest w stanie oszacować wymagań dla aktualizacji. Zostanie ona "
"teraz przerwana, a stan systemu przywrócony.\n"
"\n"
"Aby zgłosić błąd, zainstaluj apport, następnie wykonaj  'apport-bug ubuntu-"
"release-upgrader'."

#: ../DistUpgrade/DistUpgradeController.py:1932
msgid "Updating repository information"
msgstr "Aktualizowanie informacji o repozytoriach"

#: ../DistUpgrade/DistUpgradeController.py:1939
msgid "Failed to add the cdrom"
msgstr "Dodanie CD-ROM nieudane"

#: ../DistUpgrade/DistUpgradeController.py:1940
msgid "Sorry, adding the cdrom was not successful."
msgstr "Dodanie napędu CD-ROM zakończone niepowodzeniem"

#: ../DistUpgrade/DistUpgradeController.py:1975
msgid "Invalid package information"
msgstr "Błędne informacje o pakietach"

#: ../DistUpgrade/DistUpgradeController.py:1976
#, python-format
msgid ""
"After updating your package information, the essential package '%s' could "
"not be located. This may be because you have no official mirrors listed in "
"your software sources, or because of excessive load on the mirror you are "
"using. See /etc/apt/sources.list for the current list of configured software "
"sources.\n"
"In the case of an overloaded mirror, you may want to try the upgrade again "
"later."
msgstr ""
"Po aktualizacji informacji o pakietach, wymagany pakiet '%s' nie został "
"znaleziony. Może to być spowodowane tym, że w Twoich źródłach oprogramowania "
"nie ma zawartych oficjalnych serwerów lustrzanych lub tym, że te, których "
"używasz są przeciążone. Przejrzyj /etc/apt/sources.list, by zobaczyć "
"aktualną listę skonfigurowanych źródeł oprogramowania.\n"
"W przypadku przeciążenia serwerów lustrzanych, warto spróbować uaktualnienia "
"później."

#: ../DistUpgrade/DistUpgradeController.py:2005
#: ../DistUpgrade/DistUpgradeController.py:2106
msgid "Fetching"
msgstr "Pobieranie"

#: ../DistUpgrade/DistUpgradeController.py:2012
#: ../DistUpgrade/DistUpgradeController.py:2035
#: ../DistUpgrade/DistUpgradeController.py:2056
#: ../DistUpgrade/DistUpgradeController.py:2110
msgid "Upgrading"
msgstr "Aktualizacja w toku"

#: ../DistUpgrade/DistUpgradeController.py:2014
msgid "Upgrade infeasible"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:2015
msgid ""
"The upgrade could not be completed, there were errors during the upgrade "
"process."
msgstr ""

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:2038
msgid "Upgrade incomplete"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:2039
msgid ""
"The upgrade has partially completed but there were errors during the upgrade "
"process."
msgstr ""

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:2061
#: ../DistUpgrade/DistUpgradeController.py:2112
#: ../DistUpgrade/DistUpgradeController.py:2118
#: ../DistUpgrade/DistUpgradeController.py:2129
msgid "Upgrade complete"
msgstr "Aktualizacja ukończona"

#: ../DistUpgrade/DistUpgradeController.py:2062
#: ../DistUpgrade/DistUpgradeController.py:2113
#: ../DistUpgrade/DistUpgradeController.py:2119
msgid ""
"The upgrade has completed but there were errors during the upgrade process."
msgstr ""
"Aktualizacja została zakończona, lecz wystąpiły błędy podczas tego procesu."

#: ../DistUpgrade/DistUpgradeController.py:2081
msgid "System upgrade is complete."
msgstr "Aktualizacja systemu zakończona powodzeniem."

#: ../DistUpgrade/DistUpgradeController.py:2130
msgid "The partial upgrade was completed."
msgstr "Częściowa aktualizacja została ukończona"

#: ../DistUpgrade/DistUpgradeController.py:2159
msgid "Lock screen disabled"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:2160
msgid ""
"Your lock screen has been disabled and will remain disabled until you reboot."
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcher.py:107
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:170
msgid "Could not find the release notes"
msgstr "Nie można było odnaleźć informacji o wydaniu"

#: ../DistUpgrade/DistUpgradeFetcher.py:108
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:171
msgid "The server may be overloaded. "
msgstr "Serwer może być przeciążony. "

#: ../DistUpgrade/DistUpgradeFetcher.py:120
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:175
msgid "Could not download the release notes"
msgstr "Pobranie informacji o wydaniu było niemożliwe"

#: ../DistUpgrade/DistUpgradeFetcher.py:121
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:176
msgid "Please check your internet connection."
msgstr "Proszę sprawdzić połączenie sieciowe."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:73
#, python-format
msgid "authenticate '%(file)s' against '%(signature)s' "
msgstr "uwierzytelnianie '%(file)s' przed '%(signature)s' "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:97
#, python-format
msgid "extracting '%s'"
msgstr "Wypakowywanie '%s'"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:118
#: ../DistUpgrade/DistUpgradeFetcherCore.py:119
msgid "Could not run the upgrade tool"
msgstr "Nie można było uruchomić narzędzia aktualizacji"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:120
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug "
"using the command 'ubuntu-bug ubuntu-release-upgrader-core'."
msgstr ""
"Prawdopodobnie wystąpił błąd narzędzia aktualizacji. Proszę zgłosić go, "
"używając komendy \"ubuntu-bug ubuntu-release-upgrader-core\""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:197
msgid "Upgrade tool signature"
msgstr "Podpis narzędzia aktualizacji"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:204
msgid "Upgrade tool"
msgstr "Narzędzie aktualizacji"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:238
msgid "Failed to fetch"
msgstr "Pobieranie nie powiodło się"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:239
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""
"Pobieranie aktualizacji nie powiodło się. Może to oznaczać problem z siecią. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:243
msgid "Authentication failed"
msgstr "Uwierzytelnienie nie powiodło się"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:244
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"Uwierzytelnienie aktualizacji nie powiodło się. Mógł wystąpić problem z "
"siecią lub z serwerem. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:249
msgid "Failed to extract"
msgstr "Rozpakowywanie nie powiodło się"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:250
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"Rozpakowywanie aktualizacji nie powiodło się. Mógł wystąpić problem z siecią "
"lub z serwerem. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:255
msgid "Verification failed"
msgstr "Weryfikacja nie powiodła się"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:256
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"Weryfikacja aktualizacji nie powiodła się. Mógł wystąpić problem z siecią "
"lub z serwerem. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:270
#: ../DistUpgrade/DistUpgradeFetcherCore.py:276
msgid "Can not run the upgrade"
msgstr "Nie można rozpocząć aktualizacji"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:271
msgid ""
"This usually is caused by a system where /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"Taka sytuacja ma najczęściej miejsce w systemie gdzie katalog /tmp jest "
"zamontowany z opcją noexec. Proszę zamontować go ponownie bez opcji noexec i "
"uruchomić aktualizację ponownie."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:277
#, python-format
msgid "The error message is '%s'."
msgstr "Treść komunikatu błędu: \\\"%s\\\""

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:151
msgid "&Upgrade"
msgstr "&aktualizacja"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:154
#: ../DistUpgrade/DistUpgradeViewKDE.py:715
msgid "&Cancel"
msgstr "&Anuluj"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:156
#: ../data/gtkbuilder/ReleaseNotes.ui.h:1
msgid "Release Notes"
msgstr "Informacje o wydaniu"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:191
msgid "Upgrade"
msgstr "Aktualizuj"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:207
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:222
msgid "Downloading additional package files..."
msgstr "Pobieranie dodatkowych plików pakietów..."

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:224
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "Plik %s z %s z prędkością %sB/s"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:228
#, python-format
msgid "File %s of %s"
msgstr "Plik %s z %s"

#. print("mediaChange %s %s" % (medium, drive))
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:235
#: ../DistUpgrade/DistUpgradeViewGtk3.py:125
#: ../DistUpgrade/DistUpgradeViewKDE.py:302
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Proszę włożyć \"%s\" do napędu \"%s\""

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:237
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:242
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:243
#: ../DistUpgrade/DistUpgradeViewKDE.py:303
msgid "Media Change"
msgstr "Zmiana nośnika"

#: ../DistUpgrade/DistUpgradeQuirks.py:226
msgid "Your graphics hardware may not be fully supported in Ubuntu 14.04."
msgstr "Twoja karta graficzna może nie być w pełni wspierana w Ubuntu 14.04"

#: ../DistUpgrade/DistUpgradeQuirks.py:228
msgid ""
"Running the 'unity' desktop environment is not fully supported by your "
"graphics hardware. You will maybe end up in a very slow environment after "
"the upgrade. Our advice is to keep the LTS version for now. For more "
"information see https://wiki.ubuntu.com/X/Bugs/"
"UpdateManagerWarningForUnity3D Do you still want to continue with the "
"upgrade?"
msgstr ""
"Używanie środowiska Unity może spowodować niepełną obsługę zasobów grafiki "
"tego komputera. Aktualizacji wersji systemu operacyjnego mogą zakończyć się "
"niesatysfakcjonującym wynikiem w postaci spowolnionej reakcji komputera. "
"Tymczasowo zalecane jest zachowanie wersji LTS. Więcje informacji na "
"stronie: https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForUnity3D Czy "
"pomimo to kontynuować proces aktualizacji?"

#: ../DistUpgrade/DistUpgradeQuirks.py:252
msgid "Your graphics hardware may not be fully supported in Ubuntu 12.04 LTS."
msgstr ""
"Bieżąca karta graficzna może nie być w pełni obsługiwana przez Ubuntu 12.04 "
"LTS."

#: ../DistUpgrade/DistUpgradeQuirks.py:254
msgid ""
"The support in Ubuntu 12.04 LTS for your Intel graphics hardware is limited "
"and you may encounter problems after the upgrade. For more information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx Do you want to "
"continue with the upgrade?"
msgstr ""
"Obsługa obecnej w komputerze karty graficznej Intel w Ubuntu 12.04 LTS  jest "
"ograniczona i mogą wystąpić z nią problemy po przeprowadzeniu aktualizacji. "
"Aby uzyskać więcej informacji, proszę odwiedzić stronę https://wiki.ubuntu."
"com/X/Bugs/UpdateManagerWarningForI8xx Kontynuować aktualizację?"

#: ../DistUpgrade/DistUpgradeQuirks.py:274
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"Aktualizacja może ograniczyć wydajność systemu dla efektów pulpitu, gier "
"oraz innych programów obciążających zasoby graficzne."

#: ../DistUpgrade/DistUpgradeQuirks.py:278
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Komputer korzysta ze sterownika grafiki AMD \"fglrx\". Brak wersji "
"sterownika z którą współpracowałby ten sprzęt w Ubuntu 10.04 LTS.\n"
"\n"
"Kontynuować?"

#: ../DistUpgrade/DistUpgradeQuirks.py:317
msgid "Sorry, no more upgrades for this system"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:318
#, python-format
msgid ""
"There will not be any further Ubuntu releases for this system's 'i386' "
"architecture.\n"
"\n"
"Updates for Ubuntu %s will continue until %s."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:333
msgid "No ARMv6 CPU"
msgstr "Brak procesora ARMv6"

#: ../DistUpgrade/DistUpgradeQuirks.py:334
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"Ten system korzysta z procesora ARM o architekturze starszej niż ARMv6. "
"Optymalizacje wszystkich pakietów w wydaniu Karmic wymagają minimalnie "
"architektury ARMv6. Nie ma możliwości aktualizacji systemu do nowego wydania "
"na tym sprzęcie."

#: ../DistUpgrade/DistUpgradeQuirks.py:354
msgid "No init available"
msgstr "Brak dostępnego procesu init"

#: ../DistUpgrade/DistUpgradeQuirks.py:355
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"Wygląda na to, że system jest uruchomiony w środowisku wirtualnym bez "
"procesu init, np. Linux-VServer. System Ubuntu 10.04 LTS nie może pracować z "
"tym typem środowiska, wymagając najpierw aktualizacji konfiguracji maszyny "
"wirtualnej."

#: ../DistUpgrade/DistUpgradeQuirks.py:396
msgid "The Robot Operating System (ROS) is installed"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:397
msgid ""
"It appears that ROS is currently installed. Each ROS release is very strict "
"about the versions of Ubuntu it supports, and Ubuntu upgrades can fail if "
"that guidance isn't followed. Before continuing, please either uninstall "
"ROS, or ensure the ROS release you have installed supports the version of "
"Ubuntu to which you're upgrading.\n"
"\n"
"For ROS 1 releases, refer to REP 3:\n"
"https://www.ros.org/reps/rep-0003.html\n"
"\n"
"For ROS 2 releases, refer to REP 2000:\n"
"https://www.ros.org/reps/rep-2000.html\n"
"\n"
"Are you sure you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:515
msgid "Connection to the Snap Store failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:516
msgid ""
"You have the package lxd installed but your system is unable to reach the "
"Snap Store. lxd is now provided via a snap and the release upgrade will fail "
"if snapd is not functional. Please make sure you're connected to the "
"Internet and update any firewall or proxy settings as needed so that you can "
"reach api.snapcraft.io. If you are an enterprise with a firewall setup you "
"may want to configure a Snap Store proxy."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:531
msgid "Connection to Snap Store failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:532
msgid ""
"Your system does not have a connection to the Snap Store. For the best "
"upgrade experience make sure that your system can connect to api.snapcraft."
"io.\n"
"Do you still want to continue with the upgrade?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:541
msgid "Outdated snapd package"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:542
msgid ""
"Your system does not have the latest version of snapd. Please update the "
"version of snapd on your system to improve the upgrade experience.\n"
"Do you still want to continue with the upgrade?"
msgstr ""

#. now perform direct API calls to the store, requesting size
#. information for each of the snaps needing installation
#: ../DistUpgrade/DistUpgradeQuirks.py:565
msgid "Calculating snap size requirements"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:596
msgid "Processing snap replacements"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:602
#, python-format
msgid "refreshing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:606
#, python-format
msgid "removing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:609
#, python-format
msgid "installing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:638
msgid "PAE not enabled"
msgstr "PAE nie jest włączony"

#: ../DistUpgrade/DistUpgradeQuirks.py:639
msgid ""
"Your system uses a CPU that does not have PAE enabled. Ubuntu only supports "
"non-PAE systems up to Ubuntu 12.04. To upgrade to a later version of Ubuntu, "
"you must enable PAE (if this is possible) see:\n"
"http://help.ubuntu.com/community/EnablingPAE"
msgstr ""
"Procesor w Twoim komputerze nie ma uruchomionego PAE. Ubuntu obsługuje takie "
"systemy tylko do wersji 12.04. W celu uaktualnienia systemu do najnowszej "
"wersji Ubuntu, proszę uruchomić PAE (jeżeli jest to możliwe), więcej "
"informacji:\n"
"http://help.ubuntu.com/community/EnablingPAE"

#: ../DistUpgrade/DistUpgradeQuirks.py:1016
msgid "Checking for installed snaps"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:58
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr ""
"Użycie podanej ścieżki do wyszukiwania CD-ROMu z pakietami aktualizacyjnymi"

#: ../DistUpgrade/DistUpgradeMain.py:64
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"Użycie nakładki graficznej. Obecnie dostępne: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:67
msgid "*DEPRECATED* this option will be ignored"
msgstr "*PRZESTARZAŁE* ta opcja zostanie zignorowana"

#: ../DistUpgrade/DistUpgradeMain.py:70
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr "Wykonaj tylko częściową aktualizację (bez nadpisywania sources.list)"

#: ../DistUpgrade/DistUpgradeMain.py:73
msgid "Disable GNU screen support"
msgstr "Wyłącz wsparcie ekranu GNU"

#: ../DistUpgrade/DistUpgradeMain.py:75
msgid "Set datadir"
msgstr "Ustaw ścieżkę do danych"

#: ../DistUpgrade/DistUpgradeMain.py:78
msgid "Upgrade to the development release"
msgstr "Aktualizuj do wydania rozwojowego"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:146
#: ../DistUpgrade/DistUpgradeViewKDE.py:316
msgid "Fetching is complete"
msgstr "Pobieranie zakończone"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:161
#: ../DistUpgrade/DistUpgradeViewKDE.py:332
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "Pobieranie %li pliku z %li z prędkością %sB/s"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:163
#: ../DistUpgrade/DistUpgradeViewGtk3.py:325
#: ../DistUpgrade/DistUpgradeViewKDE.py:333
#: ../DistUpgrade/DistUpgradeViewKDE.py:483
#, python-format
msgid "About %s remaining"
msgstr "Pozostało około %s"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:166
#: ../DistUpgrade/DistUpgradeViewKDE.py:335
#, python-format
msgid "Fetching file %li of %li"
msgstr "Pobieranie pliku %li z %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk3.py:198
#: ../DistUpgrade/DistUpgradeViewKDE.py:373
msgid "Applying changes"
msgstr "Zatwierdzanie zmian"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk3.py:224
#: ../DistUpgrade/DistUpgradeViewKDE.py:386
msgid "dependency problems - leaving unconfigured"
msgstr "problemy z zależnościami - pozostawiony nieskonfigurowany"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:229
#: ../DistUpgrade/DistUpgradeViewKDE.py:388
#, python-format
msgid "Could not install '%s'"
msgstr "Nie można było zainstalować \"%s\""

#: ../DistUpgrade/DistUpgradeViewGtk3.py:230
#: ../DistUpgrade/DistUpgradeViewKDE.py:389
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""
"Aktualizacja będzie kontynuowana, ale pakiet \"%s\" może znajdować się w "
"stanie nienadającym się do pracy. Proszę rozważyć zgłoszenie raportu błędu "
"na ten temat."

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk3.py:247
#: ../DistUpgrade/DistUpgradeViewKDE.py:411
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"Zastąpić własny plik konfiguracji\n"
"\"%s\"?"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:248
#: ../DistUpgrade/DistUpgradeViewKDE.py:412
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"Zostaną utracone wszystkie zmiany wprowadzone w tym pliku konfiguracyjnym, "
"jeśli zostanie wybrana jego zamiana na nowszą wersję."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:268
#: ../DistUpgrade/DistUpgradeViewKDE.py:435
msgid "The 'diff' command was not found"
msgstr "Polecenie \"diff\" nie zostało odnalezione"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:535
#: ../DistUpgrade/DistUpgradeViewText.py:140
msgid "A fatal error occurred"
msgstr "Wystąpił błąd krytyczny"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:536
msgid ""
"Please report this as a bug (if you haven't already) and include the files /"
"var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Proszę wypełnić raport błędu (jeśli nie zostało to jeszcze zrobione) i "
"dołączyć w nim pliki var/log/dist-upgrade/main.log i /var/log/dist-upgrade/"
"apt.log. Aktualizacja została przerwana.\n"
"Pierwotny plik sources.list został zapisany w /etc/apt/sources.list."
"distUpgrade."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:566
msgid "Ctrl-c pressed"
msgstr "Wciśnięto Ctrl-C"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:567
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"Działanie zostanie przerwane i może pozostawić system w uszkodzonym stanie. "
"Na pewno chcesz to zrobić?"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk3.py:706
msgid "To prevent data loss close all open applications and documents."
msgstr ""
"Aby zapobiec utracie danych proszę zamknąć wszystkie otwarte programy i "
"dokumenty."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:720
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr "Już nie jest wspierane przez firmę Canonical (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:721
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr "<b>Zainstaluj poprzednią wersję (%s)</b>"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:722
#, python-format
msgid "Remove (%s)"
msgstr "Usuń (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:723
#, python-format
msgid "No longer needed (%s)"
msgstr "Już nie jest potrzebne (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:724
#, python-format
msgid "Install (%s)"
msgstr "Zainstaluj (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:725
#, python-format
msgid "Upgrade (%s)"
msgstr "Zaktualizuj (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:773
msgid "Cancel"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewGtk3.py:774
#: ../DistUpgrade/DistUpgradeViewKDE.py:939
msgid "Continue"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:447
msgid "Show Difference >>>"
msgstr "Wyświetl różnicę >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:450
msgid "<<< Hide Difference"
msgstr "<<< Ukryj różnicę"

#: ../DistUpgrade/DistUpgradeViewKDE.py:701
msgid "Error"
msgstr "Wystąpił błąd"

#: ../DistUpgrade/DistUpgradeViewKDE.py:719
#: ../DistUpgrade/DistUpgradeViewKDE.py:960
msgid "&Close"
msgstr "&Zakończ"

#: ../DistUpgrade/DistUpgradeViewKDE.py:753
msgid "Show Terminal >>>"
msgstr "Wyświetl terminal >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:756
msgid "<<< Hide Terminal"
msgstr "<<< Ukryj terminal"

#: ../DistUpgrade/DistUpgradeViewKDE.py:829
msgid "Information"
msgstr "Informacje"

#: ../DistUpgrade/DistUpgradeViewKDE.py:877
msgid "&Start Upgrade"
msgstr "&uruchom aktualizację"

#: ../DistUpgrade/DistUpgradeViewKDE.py:879
#: ../DistUpgrade/DistUpgradeViewKDE.py:923
#: ../DistUpgrade/DistUpgradeViewKDE.py:926
#: ../data/gtkbuilder/DistUpgrade.ui.h:7
msgid "Details"
msgstr "Szczegóły"

#: ../DistUpgrade/DistUpgradeViewKDE.py:901
#, python-format
msgid "No longer supported %s"
msgstr "Już nie jest obsługiwane (%s)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:903
#, python-format
msgid "Remove %s"
msgstr "Usuń %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:905
#: ../DistUpgrade/DistUpgradeViewText.py:239
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "Usuń (było automatycznie zainstalowane) %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:907
#, python-format
msgid "Install %s"
msgstr "Instaluj %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:909
#, python-format
msgid "Upgrade %s"
msgstr "Aktualizuj %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:956
#: ../DistUpgrade/DistUpgradeViewText.py:292
msgid "Restart required"
msgstr "Wymagane ponowne uruchomienie komputera"

#: ../DistUpgrade/DistUpgradeViewKDE.py:956
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr ""
"<b><big>Uruchom ponownie komputer w celu zakończenia aktualizacji</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:959
#: ../data/gtkbuilder/DistUpgrade.ui.h:14
msgid "_Restart Now"
msgstr "_Uruchom ponownie"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:977
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>Czy przerwać bieżącą aktualizację ?</big></b>\n"
"\n"
"System może utracić stabilność jeśli przerwiesz aktualizację. Wskazane jest "
"wznowienie aktualizacji."

#: ../DistUpgrade/DistUpgradeViewKDE.py:981
msgid "Cancel Upgrade?"
msgstr "Anulować aktualizację?"

#: ../DistUpgrade/DistUpgradeView.py:82
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li dzień"
msgstr[1] "%li dni"
msgstr[2] "%li dni"

#: ../DistUpgrade/DistUpgradeView.py:84
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li godzina"
msgstr[1] "%li godziny"
msgstr[2] "%li godzin"

#: ../DistUpgrade/DistUpgradeView.py:86
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li minuta"
msgstr[1] "%li minuty"
msgstr[2] "%li minut"

#: ../DistUpgrade/DistUpgradeView.py:87
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li sekunda"
msgstr[1] "%li sekundy"
msgstr[2] "%li sekund"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:103
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:121
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:172
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"Pobieranie potrwa około %s używając połączenia 1 Mbit DSL lub około %s "
"używając połączenia modemowego 56k."

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:176
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "Pobieranie może potrwać około %s w przypadku tego łącza. "

#. Declare these translatable strings from the .ui files here so that
#. xgettext picks them up.
#: ../DistUpgrade/DistUpgradeView.py:270 ../data/gtkbuilder/DistUpgrade.ui.h:22
msgid "Preparing to upgrade"
msgstr "Przygotowywanie do aktualizacji"

#: ../DistUpgrade/DistUpgradeView.py:271
msgid "Getting new software channels"
msgstr "Pobieranie nowych kanałów oprogramowania"

#: ../DistUpgrade/DistUpgradeView.py:272 ../data/gtkbuilder/DistUpgrade.ui.h:24
msgid "Getting new packages"
msgstr "Pobieranie nowych pakietów"

#: ../DistUpgrade/DistUpgradeView.py:273 ../data/gtkbuilder/DistUpgrade.ui.h:27
msgid "Installing the upgrades"
msgstr "Instalowanie aktualizacji"

#: ../DistUpgrade/DistUpgradeView.py:274 ../data/gtkbuilder/DistUpgrade.ui.h:26
msgid "Cleaning up"
msgstr "Czyszczenie"

#: ../DistUpgrade/DistUpgradeView.py:363
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
"%(amount)d zainstalowany pakiet nie jest już obsługiwany przez firmę "
"Canonical. Nadal można uzyskać wsparcie od społeczności."
msgstr[1] ""
"%(amount)d zainstalowane pakiety nie są już obsługiwane przez firmę "
"Canonical. Nadal można uzyskać wsparcie od społeczności."
msgstr[2] ""
"%(amount)d zainstalowanych pakietów nie jest już obsługiwanych przez firmę "
"Canonical. Nadal można uzyskać wsparcie od społeczności."

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:372
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "%d pakiet zostanie usunięty."
msgstr[1] "%d pakiety zostaną usunięte."
msgstr[2] "%d pakietów zostanie usuniętych."

#: ../DistUpgrade/DistUpgradeView.py:377
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "%d nowy pakiet zostanie zainstalowany."
msgstr[1] "%d nowe pakiety zostaną zainstalowane."
msgstr[2] "%d nowych pakietów zostanie zainstalowanych."

#: ../DistUpgrade/DistUpgradeView.py:383
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "%d pakiet zostanie zaktualizowany."
msgstr[1] "%d pakiety zostaną zaktualizowane."
msgstr[2] "%d pakietów zostanie zaktualizowanych."

#: ../DistUpgrade/DistUpgradeView.py:391
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Konieczne pobranie w sumie %s. "

#: ../DistUpgrade/DistUpgradeView.py:396
msgid ""
"Installing the upgrade can take several hours. Once the download has "
"finished, the process cannot be canceled."
msgstr ""
"Aktualizowanie systemu może potrwać kilka godzin. Procesu nie będzie można "
"anulować po zakończeniu pobierania danych."

#: ../DistUpgrade/DistUpgradeView.py:400
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be canceled."
msgstr ""
"Pobieranie i aktualizowanie systemu może potrwać kilka godzin. Procesu nie "
"będzie można anulować po zakończeniu pobierania danych."

#: ../DistUpgrade/DistUpgradeView.py:405
msgid "Removing the packages can take several hours. "
msgstr "Usuwanie pakietów może potrwać kilka godzin. "

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:410
msgid "The software on this computer is up to date."
msgstr "Oprogramowanie tego komputera jest w pełni zaktualizowane"

#: ../DistUpgrade/DistUpgradeView.py:411
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr "Brak dostępnych aktualizacji. Aktualizacja zostanie anulowana."

#: ../DistUpgrade/DistUpgradeView.py:427
msgid "Reboot required"
msgstr "Wymagane ponowne uruchomienie komputera"

#: ../DistUpgrade/DistUpgradeView.py:428
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"Aktualizacja została ukończona i należy ponownie uruchomić komputer. "
"Uruchomić ponownie teraz?"

#: ../DistUpgrade/DistUpgradeViewText.py:82
#, python-format
msgid "Progress: [%3i%%]"
msgstr "Postęp: [%3i%%]"

#: ../DistUpgrade/DistUpgradeViewText.py:141
msgid ""
"Please report this as a bug and include the files /var/log/dist-upgrade/main."
"log and /var/log/dist-upgrade/apt.log in your report. The upgrade has "
"aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Proszę wypełnić raport błędu i dołączyć do niego pliki /var/log/dist-upgrade/"
"main.log i /var/log/dist-upgrade/apt.log. Aktualizacja została przerwana.\n"
"Pierwotny plik sources.list został zapisany w /etc/apt/sources.list."
"distUpgrade."

#: ../DistUpgrade/DistUpgradeViewText.py:165
msgid "Aborting"
msgstr "Anulowanie"

#: ../DistUpgrade/DistUpgradeViewText.py:171
msgid "Demoted:\n"
msgstr "Zdegradowane:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:178
msgid "To continue please press [ENTER]"
msgstr "Aby kontynuować, naciśnij ENTER"

#: ../DistUpgrade/DistUpgradeViewText.py:215
#: ../DistUpgrade/DistUpgradeViewText.py:253
#: ../DistUpgrade/DistUpgradeViewText.py:261
msgid "Continue [yN] "
msgstr "Kontynuuj [tN] "

#: ../DistUpgrade/DistUpgradeViewText.py:215
#: ../DistUpgrade/DistUpgradeViewText.py:253
msgid "Details [d]"
msgstr "Szczegóły [s]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:219
#: ../DistUpgrade/DistUpgradeViewText.py:264
msgid "y"
msgstr "t"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:222
#: ../DistUpgrade/DistUpgradeViewText.py:271
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:225
msgid "d"
msgstr "s"

#: ../DistUpgrade/DistUpgradeViewText.py:230
#, python-format
msgid "No longer supported: %s\n"
msgstr "Już nie jest obsługiwane: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:235
#, python-format
msgid "Remove: %s\n"
msgstr "Usuń: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:245
#, python-format
msgid "Install: %s\n"
msgstr "Instaluj: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:250
#, python-format
msgid "Upgrade: %s\n"
msgstr "Aktualizuj: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:268
msgid "Continue [Yn] "
msgstr "Kontynuować [Tn] "

#: ../DistUpgrade/DistUpgradeViewText.py:293
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"Aby ukończyć aktualizację należy uruchomić ponownie komputer.\n"
"Po wybraniu \"t\" komputer zostanie uruchomiony ponownie."

#: ../DistUpgrade/GtkProgress.py:71
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "Pobieranie pliku %(current)li z %(total)li z prędkością %(speed)s/s"

#: ../DistUpgrade/GtkProgress.py:77
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "Pobieranie pliku %(current)li z %(total)li"

#: ../data/gtkbuilder/AcquireProgress.ui.h:1
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:7
msgid "Show progress of individual files"
msgstr "Postęp pobierania poszczególnych plików"

#: ../data/gtkbuilder/DistUpgrade.ui.h:1
msgid "_Cancel Upgrade"
msgstr "_Przerwij aktualizację"

#: ../data/gtkbuilder/DistUpgrade.ui.h:2
msgid "_Resume Upgrade"
msgstr "_Wznów aktualizację"

#: ../data/gtkbuilder/DistUpgrade.ui.h:3
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>Przerwać trwającą aktualizację?</big></b>\n"
"\n"
"System może stać się niezdatny do użytku jeśli aktualizacja zostanie "
"przerwana. Zalecane jest kontynuowanie aktualizacji."

#: ../data/gtkbuilder/DistUpgrade.ui.h:6
msgid "_Start Upgrade"
msgstr "_Rozpocznij aktualizację"

#: ../data/gtkbuilder/DistUpgrade.ui.h:9
msgid "_Replace"
msgstr "Zas_tąp"

#: ../data/gtkbuilder/DistUpgrade.ui.h:10
msgid "Difference between the files"
msgstr "Różnice pomiędzy plikami"

#: ../data/gtkbuilder/DistUpgrade.ui.h:11
msgid "_Report Bug"
msgstr "Zgłoś _błąd"

#: ../data/gtkbuilder/DistUpgrade.ui.h:12
msgid "_Continue"
msgstr "K_ontynuuj"

#: ../data/gtkbuilder/DistUpgrade.ui.h:13
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>Rozpocząć aktualizację?</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:15
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>Uruchom ponownie komputer w celu zakończenia aktualizacji</big></b>\n"
"\n"
"Proszę zapisać swoją pracę przed kontynuacją."

#: ../data/gtkbuilder/DistUpgrade.ui.h:18
msgid "Distribution Upgrade"
msgstr "Aktualizacja dystrybucji"

#: ../data/gtkbuilder/DistUpgrade.ui.h:20
#, no-c-format
msgid "<b><big>Upgrading Ubuntu to version %s</big></b>"
msgstr "<b><big>Aktualizacja Ubuntu do wersji %s</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:21
msgid "    "
msgstr "    "

#: ../data/gtkbuilder/DistUpgrade.ui.h:23
msgid "Setting new software channels"
msgstr "Ustawianie nowych kanałów oprogramowania"

#: ../data/gtkbuilder/DistUpgrade.ui.h:25
msgid "Restarting the computer"
msgstr "Ponowne uruchamianie komputera"

#: ../data/gtkbuilder/DistUpgrade.ui.h:28
msgid "Terminal"
msgstr "Terminal"

#: ../data/gtkbuilder/ReleaseNotes.ui.h:2
msgid "_Upgrade"
msgstr "_Aktualizuj"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:1
msgid "<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr "<b>Nowa wersja Ubuntu jest dostępna. Dokonać aktualizacji?</b>"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:2
msgid "Don't Upgrade"
msgstr "Nie aktualizuj"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:3
msgid "Ask Me Later"
msgstr "Spytaj później"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:4
msgid "Yes, Upgrade Now"
msgstr "Tak, zaktualizuj teraz"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:5
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "Zrezygnowano z aktualizacji do nowego wydania Ubuntu"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:6
msgid ""
"You can upgrade at a later time by opening Software Updater and click on "
"\"Upgrade\"."
msgstr ""
"Można podjąć aktualizację później, otwierając program Aktualizacje "
"oprogramowania i klikając przycisk „Zaktualizuj”."

#: ../data/com.ubuntu.release-upgrader.policy.in.h:1
msgid "Perform a release upgrade"
msgstr "Zaktualizuj wydanie"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:2
msgid "To upgrade Ubuntu, you need to authenticate."
msgstr "Aby zaktualizować Ubuntu, musisz podać hasło."

#: ../data/com.ubuntu.release-upgrader.policy.in.h:3
msgid "Perform a partial upgrade"
msgstr "Zaktualizuj wydanie częściowo"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:4
msgid "To perform a partial upgrade, you need to authenticate."
msgstr "Aby przeprowadzić częściową aktualizację, musisz podać hasło."

#: ../do-partial-upgrade:75 ../do-release-upgrade:80
msgid "Show version and exit"
msgstr "Wypisuje informacje o wersji i kończy"

#: ../do-partial-upgrade:78 ../do-release-upgrade:87
msgid "Directory that contains the data files"
msgstr "Katalog zawierający pliki danych"

#: ../do-partial-upgrade:81 ../do-release-upgrade:100
msgid "Run the specified frontend"
msgstr "Uruchom określoną nakładkę"

#: ../do-partial-upgrade:112
msgid "Running partial upgrade"
msgstr "Częściowa aktualizacja w toku"

#: ../do-release-upgrade:34 ../do-release-upgrade:46
msgid "Downloading the release upgrade tool"
msgstr "Pobieranie narzędzia aktualizacji wydania"

#: ../do-release-upgrade:83
msgid ""
"If using the latest supported release, upgrade to the development release"
msgstr ""

#: ../do-release-upgrade:90 ../check_new_release_gtk.py:181
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"Zaktualizuj do najnowszej wersji, używając aktualizatora z $distro-proposed"

#: ../do-release-upgrade:94
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"Uruchom w specjalnym trybie aktualizacji.\n"
"Obecnie obsługiwane są tryby \"desktop\" dla komputerów biurkowych i \"server"
"\" dla aktualizacji serwerów."

#: ../do-release-upgrade:103
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""
"Sprawdź tylko, czy nowa wersja dystrybucji jest dostępna i przekaż rezultat "
"poprzez kod wyjścia"

#: ../do-release-upgrade:108
msgid ""
"Try the upgrade with third party mirrors and repositories enabled instead of "
"commenting them out."
msgstr ""

#: ../do-release-upgrade:122
msgid "The options --devel-release and --proposed are"
msgstr "Opcje --devel-release i --proposed"

#: ../do-release-upgrade:123
msgid "mutually exclusive. Please use only one of them."
msgstr "wzajemnie się wykluczają. Proszę użyć tylko jednej z nich."

#: ../do-release-upgrade:127
msgid "Checking for a new Ubuntu release"
msgstr "Sprawdzanie dostępności nowego wydania Ubuntu"

#: ../do-release-upgrade:139
msgid "Your Ubuntu release is not supported anymore."
msgstr "Bieżące wydanie Ubuntu nie jest już obsługiwane."

#: ../do-release-upgrade:140
msgid ""
"For upgrade information, please visit:\n"
"%(url)s\n"
msgstr ""
"Aby uzyskać informacje o aktualizacji, proszę odwiedzić adres:\n"
"%(url)s\n"

#: ../do-release-upgrade:147
msgid "In /etc/update-manager/release-upgrades Prompt "
msgstr ""

#: ../do-release-upgrade:148
msgid "is set to never so upgrading is not possible."
msgstr ""

#: ../do-release-upgrade:150
msgid "There is no development version of an LTS available."
msgstr ""

#: ../do-release-upgrade:151
msgid "To upgrade to the latest non-LTS development release "
msgstr ""

#: ../do-release-upgrade:152
msgid "set Prompt=normal in /etc/update-manager/release-upgrades."
msgstr ""

#: ../do-release-upgrade:154
msgid "Upgrades to the development release are only "
msgstr ""

#: ../do-release-upgrade:155
msgid "available from the latest supported release."
msgstr ""

#: ../do-release-upgrade:157
msgid "No new release found."
msgstr ""

#: ../do-release-upgrade:162
msgid "Release upgrade not possible right now"
msgstr "Zaktualizowanie wydania jest teraz niemożliwe"

#: ../do-release-upgrade:163
#, c-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr ""
"Aktualizacja dystrybucji nie może zostać wykonana, proszę spróbować później. "
"Komunikat serwera: \"%s\""

#: ../do-release-upgrade:169
#, c-format
msgid "New release '%s' available."
msgstr "Dostępne nowe wydanie „%s”"

#: ../do-release-upgrade:170
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "Proszę uruchomić \"do-release-upgrade\", aby zaktualizować."

#: ../do-release-upgrade:187
msgid "Please install all available updates for your release before upgrading."
msgstr ""

#: ../do-release-upgrade:203
msgid ""
"You have not rebooted after updating a package which requires a reboot. "
"Please reboot before upgrading."
msgstr ""

#: ../check_new_release_gtk.py:85
msgid "Software Updater"
msgstr "Aktualizacje oprogramowania"

#: ../check_new_release_gtk.py:113
#, python-format
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "Dostępna jest aktualizacja do Ubuntu %(version)s"

#. print("don't upgrade")
#: ../check_new_release_gtk.py:144
#, python-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "Zrezygnowano z aktualizacji do Ubuntu %s"

#: ../check_new_release_gtk.py:177
msgid "Check if upgrading to the latest devel release is possible"
msgstr "Sprawdź możliwość aktualizacji do najnowszej wersji testowej"

#: ../check_new_release_gtk.py:186
msgid "Add debug output"
msgstr "Dodaj informacje wyjściowe debugowania"

#~ msgid ""
#~ "An unresolvable problem occurred while calculating the upgrade:\n"
#~ "%s\n"
#~ "\n"
#~ " This can be caused by:\n"
#~ " * Upgrading to a pre-release version of Ubuntu\n"
#~ " * Running the current pre-release version of Ubuntu\n"
#~ " * Unofficial software packages not provided by Ubuntu\n"
#~ "\n"
#~ msgstr ""
#~ "Wystąpił nierozwiązywalny problem podczas obliczania aktualizacji:\n"
#~ "%s\n"
#~ "\n"
#~ " Może to być spowodowane przez:\n"
#~ " * aktualizowanie do testowej wersji Ubuntu,\n"
#~ " * użytkowanie bieżącej testowej wersji Ubuntu,\n"
#~ " * użytkowanie nieoficjalnych pakietów spoza repozytoriów Ubuntu.\n"
#~ "\n"

#~ msgid ""
#~ "Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
#~ "desktop or edubuntu-desktop package and it was not possible to detect "
#~ "which version of Ubuntu you are running.\n"
#~ " Please install one of the packages above first using synaptic or apt-get "
#~ "before proceeding."
#~ msgstr ""
#~ "System nie zawiera pakietów ubuntu-desktop, kubuntu-desktop, xubuntu-"
#~ "desktop lub edubuntu-desktop i nie jest możliwe wykrycie używanej wersji "
#~ "Ubuntu.\n"
#~ " Proszę zainstalować jeden z tych pakietów używając programu Synaptic lub "
#~ "apt-get przed kontynuowaniem."

#~ msgid "Sandbox setup failed"
#~ msgstr "Ustawienie trybu testowego nie powiodło się"

#~ msgid "Sandbox mode"
#~ msgstr "Tryb testowy"

#~ msgid ""
#~ "This upgrade is running in sandbox (test) mode. All changes are written "
#~ "to '%s' and will be lost on the next reboot.\n"
#~ "\n"
#~ "*No* changes written to a system directory from now until the next reboot "
#~ "are permanent."
#~ msgstr ""
#~ "Niniejsza aktualizacja wersji pracuje w trybie testowym (sandbox). "
#~ "Wszystkie zmiany zapisywane są do '%s' i zostaną utracone po ponownym "
#~ "uruchomieniu komputera.\n"
#~ "\n"
#~ "Od tej chwili *żadne* zmiany tworzone w katalogu systemu nie są trwałe, "
#~ "dopóki komputer nie zostanie uruchomiony ponownie."

#~ msgid ""
#~ "Your python install is corrupted. Please fix the '/usr/bin/python' "
#~ "symlink."
#~ msgstr ""
#~ "Instalacja python jest uszkodzona. Proszę naprawić dowiązanie do \"/usr/"
#~ "bin/python\"."

#~ msgid "Package 'debsig-verify' is installed"
#~ msgstr "Pakiet \"debsig-verify\" jest zainstalowany"

#~ msgid ""
#~ "The upgrade can not continue with that package installed.\n"
#~ "Please remove it with synaptic or 'apt-get remove debsig-verify' first "
#~ "and run the upgrade again."
#~ msgstr ""
#~ "Aktualizacja nie może być kontynuowana, podczas gdy ten pakiet jest "
#~ "zainstalowany.\n"
#~ "Proszę najpierw usunąć go używając programu Synaptic lub \"apt-get remove "
#~ "debsig-verify\", a następnie uruchomić ponownie aktualizację\"."

#~ msgid ""
#~ "While scanning your repository information no mirror entry for the "
#~ "upgrade was found. This can happen if you run a internal mirror or if the "
#~ "mirror information is out of date.\n"
#~ "\n"
#~ "Do you want to rewrite your 'sources.list' file anyway? If you choose "
#~ "'Yes' here it will update all '%s' to '%s' entries.\n"
#~ "If you select 'No' the upgrade will cancel."
#~ msgstr ""
#~ "Podczas przetwarzania informacji o repozytoriach nie odnaleziono wpisu "
#~ "serwera lustrzanego do aktualizacji. Może się tak zdarzyć, gdy używamy "
#~ "wewnętrznego serwera lustrzanego lub jeśli informacje o serwerach są "
#~ "nieaktualne.\n"
#~ "\n"
#~ "Przepisać plik \"sources.list\" mimo to? Wybranie \"Tak\" oznacza "
#~ "aktualizację wszystkich wpisów \"%s\" do \"%s\".\n"
#~ "Wybranie \"Nie\" anuluje aktualizację."

#~ msgid ""
#~ "The upgrade has aborted. The upgrade needs a total of %s free space on "
#~ "disk '%s'. Please free at least an additional %s of disk space on '%s'. "
#~ "Empty your trash and remove temporary packages of former installations "
#~ "using 'sudo apt-get clean'."
#~ msgstr ""
#~ "Aktualizacja została przerwana. Aktualizacja wymaga ogółem %s wolnego "
#~ "miejsca na dysku \"%s\". Proszę uwolnić przynajmniej %s dodatkowego "
#~ "wolnego miejsca na \"%s\". Należy opróżnić kosz i usunąć tymczasowe "
#~ "pakiety z poprzednich instalacji używając polecenia \"sudo apt-get clean"
#~ "\"."

#~ msgid "evms in use"
#~ msgstr "EVMS w użyciu"

#~ msgid ""
#~ "Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
#~ "software is no longer supported, please switch it off and run the upgrade "
#~ "again when this is done."
#~ msgstr ""
#~ "Twój system używa managera woluminów EVMS w /proc/mounts. Oprogramowanie "
#~ "EVMS nie jest więcej wspierane. W związku z tym należy je wyłączyć i "
#~ "zaktualizować, a po jej zakończeniu włączyć go ponownie."

#~ msgid ""
#~ "This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
#~ "version of this driver is available that works with your video card in "
#~ "Ubuntu 10.04 LTS.\n"
#~ "\n"
#~ "Do you want to continue?"
#~ msgstr ""
#~ "Komputer korzysta ze sterownika grafiki NVIDIA \"nvidia\". Brak wersji "
#~ "sterownika z którą współpracowałby ten sprzęt w Ubuntu 10.04 LTS.\n"
#~ "\n"
#~ "Kontynuować?"

#~ msgid "No i686 CPU"
#~ msgstr "Brak procesora o architekturze i686"

#~ msgid ""
#~ "Your system uses an i586 CPU or a CPU that does not have the 'cmov' "
#~ "extension. All packages were built with optimizations requiring i686 as "
#~ "the minimal architecture. It is not possible to upgrade your system to a "
#~ "new Ubuntu release with this hardware."
#~ msgstr ""
#~ "Twój system używa procesora o architekturze i586 lub twój procesor nie "
#~ "posiada rozszerzenia 'cmov'. Wszystkie pakiety zostały zbudowane w "
#~ "oparciu o optymalizacje wymagające minimum architektury i686. Na tym "
#~ "sprzęcie niemożliwa jest aktualizacja twojego systemu do nowego wydania "
#~ "Ubuntu."

#~ msgid "Sandbox upgrade using aufs"
#~ msgstr "Aktualizacja testowa używając aufs"

#~ msgid "Test upgrade with a sandbox aufs overlay"
#~ msgstr "Aktualizacja testowa z nakładką sandbox aufs"

#~ msgid "No new release found"
#~ msgstr "Nie odnaleziono nowego wydania"

#~ msgid "Authentication is required to perform a release upgrade"
#~ msgstr "Wymagane jest uwierzytelnienie w celu zaktualizowania wydania"

#~ msgid ""
#~ "If none of this applies, then please report this bug using the command "
#~ "'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
#~ msgstr ""
#~ "Jeśli żadna z wymienionych sytuacji nie ma miejsca, proszę zgłosić ten "
#~ "błąd wprowadzając w terminalu polecenie „ubuntu-bug ubuntu-release-"
#~ "upgrader-core”."

#~ msgid "It was not possible to create the sandbox environment."
#~ msgstr "Utworzenie testowego środowiska nie było możliwe."

#~ msgid "Authentication is required to perform a partial upgrade"
#~ msgstr ""
#~ "Wymagane jest uwierzytelnienie w celu częściowego zaktualizowania wydania"

#~ msgid "Your graphics hardware may not be fully supported in Ubuntu 13.04."
#~ msgstr ""
#~ "W Ubuntu 13.04 urządzenia grafiki tego komputera mogą nie być w pełni "
#~ "obsługiwane."

#~ msgid "<b><big>Upgrading Ubuntu to version 13.04</big></b>"
#~ msgstr "<b><big>Aktualizacja wersji Ubuntu do wersji 13.04</big></b>"

#~ msgid ""
#~ "An unresolvable problem occurred while calculating the upgrade.\n"
#~ "\n"
#~ " This can be caused by:\n"
#~ " * Upgrading to a pre-release version of Ubuntu\n"
#~ " * Running the current pre-release version of Ubuntu\n"
#~ " * Unofficial software packages not provided by Ubuntu\n"
#~ "\n"
#~ msgstr ""
#~ "Wystąpił niemożliwy do rozwiązania problem podczas aktualizacji.\n"
#~ "\n"
#~ "Może on być spowodowany przez:\n"
#~ "* Aktualizowanie do testowej wersji Ubuntu\n"
#~ "* Działanie na testowej wersji Ubuntu\n"
#~ "* Nieoficjalne pakiety oprogramowania niedostarczane przez Ubuntu\n"
#~ "\n"

#~ msgid "<b><big>Upgrading Ubuntu to version 15.04</big></b>"
#~ msgstr "<b><big>Aktualizacja Ubuntu do wersji 15.04</big></b>"

#~ msgid "<b><big>Upgrading Ubuntu to version 15.10</big></b>"
#~ msgstr "<b><big>Aktualizacja Ubuntu do wersji 15.10</big></b>"
